* Path 1

** Conditions
(iszero (callvalue))
(eq? ("transferFrom" 599290589) ("signature" (div (exp 224 2) (calldataload 0))))
(div (or ("to" (calldataload 36)) ("from" (calldataload 4))) (exp 160 2))

** Outcome Bad "reverted"

** Storage
(initial)

* Path 2

** Conditions
(iszero (callvalue))
(eq? ("transferFrom" 599290589) ("signature" (div (exp 224 2) (calldataload 0))))
(not (div (or ("to" (calldataload 36)) ("from" (calldataload 4))) (exp 160 2)))
(< 
  ("source balance" (sload ("from" (calldataload 4)) (initial)))
  ("value to be transferred" (calldataload 68)))

** Outcome Bad "reverted"

** Storage
(initial)

* Path 3

** Conditions
(iszero (callvalue))
(eq? ("transferFrom" 599290589) ("signature" (div (exp 224 2) (calldataload 0))))
(not (div (or ("to" (calldataload 36)) ("from" (calldataload 4))) (exp 160 2)))
(not 
  (< 
    ("source balance" (sload ("from" (calldataload 4)) (initial)))
    ("value to be transferred" (calldataload 68))))
(eq? (caller) ("from" (calldataload 4)))
("overflow" 
  (< 
    ("target balance" (sload ("to" (calldataload 36)) (initial)))
    (+ 
      ("target balance" (sload ("to" (calldataload 36)) (initial)))
      ("value to be transferred" (calldataload 68)))))

** Outcome Bad "reverted"

** Storage
(set 
  ("target balance" (sload ("to" (calldataload 36)) (initial)))
  (- ("value to be transferred" (calldataload 68)) ("from" (calldataload 4)))
  (initial))

* Path 4

** Conditions
(iszero (callvalue))
(eq? ("transferFrom" 599290589) ("signature" (div (exp 224 2) (calldataload 0))))
(not (div (or ("to" (calldataload 36)) ("from" (calldataload 4))) (exp 160 2)))
(not 
  (< 
    ("source balance" (sload ("from" (calldataload 4)) (initial)))
    ("value to be transferred" (calldataload 68))))
(eq? (caller) ("from" (calldataload 4)))
(not 
  ("overflow" 
    (< 
      ("target balance" (sload ("to" (calldataload 36)) (initial)))
      (+ 
        ("target balance" (sload ("to" (calldataload 36)) (initial)))
        ("value to be transferred" (calldataload 68))))))

** Outcome Good

** Storage
(set 
  ("to" (calldataload 36))
  (+ 
    ("target balance" (sload ("to" (calldataload 36)) (initial)))
    ("value to be transferred" (calldataload 68)))
  (set 
    ("target balance" (sload ("to" (calldataload 36)) (initial)))
    (- ("value to be transferred" (calldataload 68)) ("from" (calldataload 4)))
    (initial)))

* Path 5

** Conditions
(iszero (callvalue))
(eq? ("transferFrom" 599290589) ("signature" (div (exp 224 2) (calldataload 0))))
(not (div (or ("to" (calldataload 36)) ("from" (calldataload 4))) (exp 160 2)))
(not 
  (< 
    ("source balance" (sload ("from" (calldataload 4)) (initial)))
    ("value to be transferred" (calldataload 68))))
(not (eq? (caller) ("from" (calldataload 4))))
(eq? 
  ("allowance" 
    (sload 
      (keccak256 0 32 (set 32 (caller) (set 0 ("from" (calldataload 4)) (initial))))
      (initial)))
  ("infinite allowance symbol" (not 1)))
("overflow" 
  (< 
    (keccak256 0 32 (set 32 (caller) (set 0 ("from" (calldataload 4)) (initial))))
    (+ 
      (keccak256 0 32 (set 32 (caller) (set 0 ("from" (calldataload 4)) (initial))))
      ("from" (calldataload 4)))))

** Outcome Bad "reverted"

** Storage
(set 
  (keccak256 0 32 (set 32 (caller) (set 0 ("from" (calldataload 4)) (initial))))
  (- 
    ("from" (calldataload 4))
    ("source balance" (sload ("from" (calldataload 4)) (initial))))
  (initial))

* Path 6

** Conditions
(iszero (callvalue))
(eq? ("transferFrom" 599290589) ("signature" (div (exp 224 2) (calldataload 0))))
(not (div (or ("to" (calldataload 36)) ("from" (calldataload 4))) (exp 160 2)))
(not 
  (< 
    ("source balance" (sload ("from" (calldataload 4)) (initial)))
    ("value to be transferred" (calldataload 68))))
(not (eq? (caller) ("from" (calldataload 4))))
(eq? 
  ("allowance" 
    (sload 
      (keccak256 0 32 (set 32 (caller) (set 0 ("from" (calldataload 4)) (initial))))
      (initial)))
  ("infinite allowance symbol" (not 1)))
(not 
  ("overflow" 
    (< 
      (keccak256 0 32 (set 32 (caller) (set 0 ("from" (calldataload 4)) (initial))))
      (+ 
        (keccak256 0 32 (set 32 (caller) (set 0 ("from" (calldataload 4)) (initial))))
        ("from" (calldataload 4))))))

** Outcome Good

** Storage
(set 
  ("target balance" (sload ("to" (calldataload 36)) (initial)))
  (+ 
    (keccak256 0 32 (set 32 (caller) (set 0 ("from" (calldataload 4)) (initial))))
    ("from" (calldataload 4)))
  (set 
    (keccak256 0 32 (set 32 (caller) (set 0 ("from" (calldataload 4)) (initial))))
    (- 
      ("from" (calldataload 4))
      ("source balance" (sload ("from" (calldataload 4)) (initial))))
    (initial)))

* Path 7

** Conditions
(iszero (callvalue))
(eq? ("transferFrom" 599290589) ("signature" (div (exp 224 2) (calldataload 0))))
(not (div (or ("to" (calldataload 36)) ("from" (calldataload 4))) (exp 160 2)))
(not 
  (< 
    ("source balance" (sload ("from" (calldataload 4)) (initial)))
    ("value to be transferred" (calldataload 68))))
(not (eq? (caller) ("from" (calldataload 4))))
(not 
  (eq? 
    ("allowance" 
      (sload 
        (keccak256 0 32 (set 32 (caller) (set 0 ("from" (calldataload 4)) (initial))))
        (initial)))
    ("infinite allowance symbol" (not 1))))
(< 
  ("allowance" 
    (sload 
      (keccak256 0 32 (set 32 (caller) (set 0 ("from" (calldataload 4)) (initial))))
      (initial)))
  ("value to be transferred" (calldataload 68)))

** Outcome Bad "reverted"

** Storage
(initial)

* Path 8

** Conditions
(iszero (callvalue))
(eq? ("transferFrom" 599290589) ("signature" (div (exp 224 2) (calldataload 0))))
(not (div (or ("to" (calldataload 36)) ("from" (calldataload 4))) (exp 160 2)))
(not 
  (< 
    ("source balance" (sload ("from" (calldataload 4)) (initial)))
    ("value to be transferred" (calldataload 68))))
(not (eq? (caller) ("from" (calldataload 4))))
(not 
  (eq? 
    ("allowance" 
      (sload 
        (keccak256 0 32 (set 32 (caller) (set 0 ("from" (calldataload 4)) (initial))))
        (initial)))
    ("infinite allowance symbol" (not 1))))
(not 
  (< 
    ("allowance" 
      (sload 
        (keccak256 0 32 (set 32 (caller) (set 0 ("from" (calldataload 4)) (initial))))
        (initial)))
    ("value to be transferred" (calldataload 68))))
("overflow" 
  (< 
    ("target balance" (sload ("to" (calldataload 36)) (initial)))
    (+ 
      ("target balance" (sload ("to" (calldataload 36)) (initial)))
      ("value to be transferred" (calldataload 68)))))

** Outcome Bad "reverted"

** Storage
(set 
  ("target balance" (sload ("to" (calldataload 36)) (initial)))
  (- ("value to be transferred" (calldataload 68)) ("from" (calldataload 4)))
  (set 
    ("source balance" (sload ("from" (calldataload 4)) (initial)))
    (- 
      ("value to be transferred" (calldataload 68))
      (keccak256 0 32 (set 32 (caller) (set 0 ("from" (calldataload 4)) (initial)))))
    (initial)))

* Path 9

** Conditions
(iszero (callvalue))
(eq? ("transferFrom" 599290589) ("signature" (div (exp 224 2) (calldataload 0))))
(not (div (or ("to" (calldataload 36)) ("from" (calldataload 4))) (exp 160 2)))
(not 
  (< 
    ("source balance" (sload ("from" (calldataload 4)) (initial)))
    ("value to be transferred" (calldataload 68))))
(not (eq? (caller) ("from" (calldataload 4))))
(not 
  (eq? 
    ("allowance" 
      (sload 
        (keccak256 0 32 (set 32 (caller) (set 0 ("from" (calldataload 4)) (initial))))
        (initial)))
    ("infinite allowance symbol" (not 1))))
(not 
  (< 
    ("allowance" 
      (sload 
        (keccak256 0 32 (set 32 (caller) (set 0 ("from" (calldataload 4)) (initial))))
        (initial)))
    ("value to be transferred" (calldataload 68))))
(not 
  ("overflow" 
    (< 
      ("target balance" (sload ("to" (calldataload 36)) (initial)))
      (+ 
        ("target balance" (sload ("to" (calldataload 36)) (initial)))
        ("value to be transferred" (calldataload 68))))))

** Outcome Good

** Storage
(set 
  ("to" (calldataload 36))
  (+ 
    ("target balance" (sload ("to" (calldataload 36)) (initial)))
    ("value to be transferred" (calldataload 68)))
  (set 
    ("target balance" (sload ("to" (calldataload 36)) (initial)))
    (- ("value to be transferred" (calldataload 68)) ("from" (calldataload 4)))
    (set 
      ("source balance" (sload ("from" (calldataload 4)) (initial)))
      (- 
        ("value to be transferred" (calldataload 68))
        (keccak256 0 32 (set 32 (caller) (set 0 ("from" (calldataload 4)) (initial)))))
      (initial))))

* Path 10

** Conditions
(iszero (callvalue))
(not 
  (eq? ("transferFrom" 599290589) ("signature" (div (exp 224 2) (calldataload 0)))))
(eq? ("approve" 157198259) ("signature" (div (exp 224 2) (calldataload 0))))

** Outcome Good

** Storage
(set 
  (calldataload 36)
  (keccak256 0 64 (set 32 (calldataload 36) (set 0 (caller) (initial))))
  (initial))

* Path 11

** Conditions
(iszero (callvalue))
(not 
  (eq? ("transferFrom" 599290589) ("signature" (div (exp 224 2) (calldataload 0)))))
(not (eq? ("approve" 157198259) ("signature" (div (exp 224 2) (calldataload 0)))))
(eq? ("withdraw" 773487949) ("signature" (div (exp 224 2) (calldataload 0))))
(> (- (calldataload 4) (sload (caller) (initial))) (sload (caller) (initial)))

** Outcome Bad "reverted"

** Storage
(initial)

* Path 12

** Conditions
(iszero (callvalue))
(not 
  (eq? ("transferFrom" 599290589) ("signature" (div (exp 224 2) (calldataload 0)))))
(not (eq? ("approve" 157198259) ("signature" (div (exp 224 2) (calldataload 0)))))
(eq? ("withdraw" 773487949) ("signature" (div (exp 224 2) (calldataload 0))))
(not (> (- (calldataload 4) (sload (caller) (initial))) (sload (caller) (initial))))
(iszero 1)

** Outcome Bad "reverted"

** Storage
(arbitrarily-altered 
  (set 
    (not 1)
    (- 
      (not 1)
      (sload (calldataload 4) (set (caller) (sload (caller) (initial)) (initial))))
    (set (caller) (sload (caller) (initial)) (initial))))

* Path 13

** Conditions
(iszero (callvalue))
(not 
  (eq? ("transferFrom" 599290589) ("signature" (div (exp 224 2) (calldataload 0)))))
(not (eq? ("approve" 157198259) ("signature" (div (exp 224 2) (calldataload 0)))))
(eq? ("withdraw" 773487949) ("signature" (div (exp 224 2) (calldataload 0))))
(not (> (- (calldataload 4) (sload (caller) (initial))) (sload (caller) (initial))))
(not (iszero 1))

** Outcome Good

** Storage
(arbitrarily-altered 
  (set 
    (not 1)
    (- 
      (not 1)
      (sload (calldataload 4) (set (caller) (sload (caller) (initial)) (initial))))
    (set (caller) (sload (caller) (initial)) (initial))))

* Path 14

** Conditions
(iszero (callvalue))
(not 
  (eq? ("transferFrom" 599290589) ("signature" (div (exp 224 2) (calldataload 0)))))
(not (eq? ("approve" 157198259) ("signature" (div (exp 224 2) (calldataload 0)))))
(not (eq? ("withdraw" 773487949) ("signature" (div (exp 224 2) (calldataload 0)))))
(eq? ("balanceOf" 1889567281) ("signature" (div (exp 224 2) (calldataload 0))))

** Outcome Good

** Storage
(initial)

* Path 15

** Conditions
(iszero (callvalue))
(not 
  (eq? ("transferFrom" 599290589) ("signature" (div (exp 224 2) (calldataload 0)))))
(not (eq? ("approve" 157198259) ("signature" (div (exp 224 2) (calldataload 0)))))
(not (eq? ("withdraw" 773487949) ("signature" (div (exp 224 2) (calldataload 0)))))
(not (eq? ("balanceOf" 1889567281) ("signature" (div (exp 224 2) (calldataload 0)))))
(eq? ("totalSupply" 404098525) ("signature" (div (exp 224 2) (calldataload 0))))

** Outcome Good

** Storage
(initial)

* Path 16

** Conditions
(iszero (callvalue))
(not 
  (eq? ("transferFrom" 599290589) ("signature" (div (exp 224 2) (calldataload 0)))))
(not (eq? ("approve" 157198259) ("signature" (div (exp 224 2) (calldataload 0)))))
(not (eq? ("withdraw" 773487949) ("signature" (div (exp 224 2) (calldataload 0)))))
(not (eq? ("balanceOf" 1889567281) ("signature" (div (exp 224 2) (calldataload 0)))))
(not (eq? ("totalSupply" 404098525) ("signature" (div (exp 224 2) (calldataload 0)))))
(eq? ("allowance" 3714247998) ("signature" (div (exp 224 2) (calldataload 0))))

** Outcome Good

** Storage
(initial)

* Path 17

** Conditions
(iszero (callvalue))
(not 
  (eq? ("transferFrom" 599290589) ("signature" (div (exp 224 2) (calldataload 0)))))
(not (eq? ("approve" 157198259) ("signature" (div (exp 224 2) (calldataload 0)))))
(not (eq? ("withdraw" 773487949) ("signature" (div (exp 224 2) (calldataload 0)))))
(not (eq? ("balanceOf" 1889567281) ("signature" (div (exp 224 2) (calldataload 0)))))
(not (eq? ("totalSupply" 404098525) ("signature" (div (exp 224 2) (calldataload 0)))))
(not (eq? ("allowance" 3714247998) ("signature" (div (exp 224 2) (calldataload 0)))))
(eq? ("transfer" 2835717307) ("signature" (div (exp 224 2) (calldataload 0))))
(div (or ("recipient" (calldataload 4)) (caller)) (exp 160 2))

** Outcome Bad "reverted"

** Storage
(initial)

* Path 18

** Conditions
(iszero (callvalue))
(not 
  (eq? ("transferFrom" 599290589) ("signature" (div (exp 224 2) (calldataload 0)))))
(not (eq? ("approve" 157198259) ("signature" (div (exp 224 2) (calldataload 0)))))
(not (eq? ("withdraw" 773487949) ("signature" (div (exp 224 2) (calldataload 0)))))
(not (eq? ("balanceOf" 1889567281) ("signature" (div (exp 224 2) (calldataload 0)))))
(not (eq? ("totalSupply" 404098525) ("signature" (div (exp 224 2) (calldataload 0)))))
(not (eq? ("allowance" 3714247998) ("signature" (div (exp 224 2) (calldataload 0)))))
(eq? ("transfer" 2835717307) ("signature" (div (exp 224 2) (calldataload 0))))
(not (div (or ("recipient" (calldataload 4)) (caller)) (exp 160 2)))
(< 
  ("source balance" (sload (caller) (initial)))
  ("value to be transferred" (calldataload 36)))

** Outcome Bad "reverted"

** Storage
(initial)

* Path 19

** Conditions
(iszero (callvalue))
(not 
  (eq? ("transferFrom" 599290589) ("signature" (div (exp 224 2) (calldataload 0)))))
(not (eq? ("approve" 157198259) ("signature" (div (exp 224 2) (calldataload 0)))))
(not (eq? ("withdraw" 773487949) ("signature" (div (exp 224 2) (calldataload 0)))))
(not (eq? ("balanceOf" 1889567281) ("signature" (div (exp 224 2) (calldataload 0)))))
(not (eq? ("totalSupply" 404098525) ("signature" (div (exp 224 2) (calldataload 0)))))
(not (eq? ("allowance" 3714247998) ("signature" (div (exp 224 2) (calldataload 0)))))
(eq? ("transfer" 2835717307) ("signature" (div (exp 224 2) (calldataload 0))))
(not (div (or ("recipient" (calldataload 4)) (caller)) (exp 160 2)))
(not 
  (< 
    ("source balance" (sload (caller) (initial)))
    ("value to be transferred" (calldataload 36))))
(eq? (caller) (caller))
("overflow" 
  (< 
    ("target balance" (sload ("recipient" (calldataload 4)) (initial)))
    (+ 
      ("target balance" (sload ("recipient" (calldataload 4)) (initial)))
      ("value to be transferred" (calldataload 36)))))

** Outcome Bad "reverted"

** Storage
(set 
  ("target balance" (sload ("recipient" (calldataload 4)) (initial)))
  (- ("value to be transferred" (calldataload 36)) (caller))
  (initial))

* Path 20

** Conditions
(iszero (callvalue))
(not 
  (eq? ("transferFrom" 599290589) ("signature" (div (exp 224 2) (calldataload 0)))))
(not (eq? ("approve" 157198259) ("signature" (div (exp 224 2) (calldataload 0)))))
(not (eq? ("withdraw" 773487949) ("signature" (div (exp 224 2) (calldataload 0)))))
(not (eq? ("balanceOf" 1889567281) ("signature" (div (exp 224 2) (calldataload 0)))))
(not (eq? ("totalSupply" 404098525) ("signature" (div (exp 224 2) (calldataload 0)))))
(not (eq? ("allowance" 3714247998) ("signature" (div (exp 224 2) (calldataload 0)))))
(eq? ("transfer" 2835717307) ("signature" (div (exp 224 2) (calldataload 0))))
(not (div (or ("recipient" (calldataload 4)) (caller)) (exp 160 2)))
(not 
  (< 
    ("source balance" (sload (caller) (initial)))
    ("value to be transferred" (calldataload 36))))
(eq? (caller) (caller))
(not 
  ("overflow" 
    (< 
      ("target balance" (sload ("recipient" (calldataload 4)) (initial)))
      (+ 
        ("target balance" (sload ("recipient" (calldataload 4)) (initial)))
        ("value to be transferred" (calldataload 36))))))

** Outcome Good

** Storage
(set 
  ("recipient" (calldataload 4))
  (+ 
    ("target balance" (sload ("recipient" (calldataload 4)) (initial)))
    ("value to be transferred" (calldataload 36)))
  (set 
    ("target balance" (sload ("recipient" (calldataload 4)) (initial)))
    (- ("value to be transferred" (calldataload 36)) (caller))
    (initial)))

* Path 21

** Conditions
(iszero (callvalue))
(not 
  (eq? ("transferFrom" 599290589) ("signature" (div (exp 224 2) (calldataload 0)))))
(not (eq? ("approve" 157198259) ("signature" (div (exp 224 2) (calldataload 0)))))
(not (eq? ("withdraw" 773487949) ("signature" (div (exp 224 2) (calldataload 0)))))
(not (eq? ("balanceOf" 1889567281) ("signature" (div (exp 224 2) (calldataload 0)))))
(not (eq? ("totalSupply" 404098525) ("signature" (div (exp 224 2) (calldataload 0)))))
(not (eq? ("allowance" 3714247998) ("signature" (div (exp 224 2) (calldataload 0)))))
(eq? ("transfer" 2835717307) ("signature" (div (exp 224 2) (calldataload 0))))
(not (div (or ("recipient" (calldataload 4)) (caller)) (exp 160 2)))
(not 
  (< 
    ("source balance" (sload (caller) (initial)))
    ("value to be transferred" (calldataload 36))))
(not (eq? (caller) (caller)))
(eq? 
  ("allowance" 
    (sload (keccak256 0 32 (set 32 (caller) (set 0 (caller) (initial)))) (initial)))
  ("infinite allowance symbol" (not 1)))
("overflow" 
  (< 
    (keccak256 0 32 (set 32 (caller) (set 0 (caller) (initial))))
    (+ (keccak256 0 32 (set 32 (caller) (set 0 (caller) (initial)))) (caller))))

** Outcome Bad "reverted"

** Storage
(set 
  (keccak256 0 32 (set 32 (caller) (set 0 (caller) (initial))))
  (- (caller) ("source balance" (sload (caller) (initial))))
  (initial))

* Path 22

** Conditions
(iszero (callvalue))
(not 
  (eq? ("transferFrom" 599290589) ("signature" (div (exp 224 2) (calldataload 0)))))
(not (eq? ("approve" 157198259) ("signature" (div (exp 224 2) (calldataload 0)))))
(not (eq? ("withdraw" 773487949) ("signature" (div (exp 224 2) (calldataload 0)))))
(not (eq? ("balanceOf" 1889567281) ("signature" (div (exp 224 2) (calldataload 0)))))
(not (eq? ("totalSupply" 404098525) ("signature" (div (exp 224 2) (calldataload 0)))))
(not (eq? ("allowance" 3714247998) ("signature" (div (exp 224 2) (calldataload 0)))))
(eq? ("transfer" 2835717307) ("signature" (div (exp 224 2) (calldataload 0))))
(not (div (or ("recipient" (calldataload 4)) (caller)) (exp 160 2)))
(not 
  (< 
    ("source balance" (sload (caller) (initial)))
    ("value to be transferred" (calldataload 36))))
(not (eq? (caller) (caller)))
(eq? 
  ("allowance" 
    (sload (keccak256 0 32 (set 32 (caller) (set 0 (caller) (initial)))) (initial)))
  ("infinite allowance symbol" (not 1)))
(not 
  ("overflow" 
    (< 
      (keccak256 0 32 (set 32 (caller) (set 0 (caller) (initial))))
      (+ (keccak256 0 32 (set 32 (caller) (set 0 (caller) (initial)))) (caller)))))

** Outcome Good

** Storage
(set 
  ("target balance" (sload ("recipient" (calldataload 4)) (initial)))
  (+ (keccak256 0 32 (set 32 (caller) (set 0 (caller) (initial)))) (caller))
  (set 
    (keccak256 0 32 (set 32 (caller) (set 0 (caller) (initial))))
    (- (caller) ("source balance" (sload (caller) (initial))))
    (initial)))

* Path 23

** Conditions
(iszero (callvalue))
(not 
  (eq? ("transferFrom" 599290589) ("signature" (div (exp 224 2) (calldataload 0)))))
(not (eq? ("approve" 157198259) ("signature" (div (exp 224 2) (calldataload 0)))))
(not (eq? ("withdraw" 773487949) ("signature" (div (exp 224 2) (calldataload 0)))))
(not (eq? ("balanceOf" 1889567281) ("signature" (div (exp 224 2) (calldataload 0)))))
(not (eq? ("totalSupply" 404098525) ("signature" (div (exp 224 2) (calldataload 0)))))
(not (eq? ("allowance" 3714247998) ("signature" (div (exp 224 2) (calldataload 0)))))
(eq? ("transfer" 2835717307) ("signature" (div (exp 224 2) (calldataload 0))))
(not (div (or ("recipient" (calldataload 4)) (caller)) (exp 160 2)))
(not 
  (< 
    ("source balance" (sload (caller) (initial)))
    ("value to be transferred" (calldataload 36))))
(not (eq? (caller) (caller)))
(not 
  (eq? 
    ("allowance" 
      (sload (keccak256 0 32 (set 32 (caller) (set 0 (caller) (initial)))) (initial)))
    ("infinite allowance symbol" (not 1))))
(< 
  ("allowance" 
    (sload (keccak256 0 32 (set 32 (caller) (set 0 (caller) (initial)))) (initial)))
  ("value to be transferred" (calldataload 36)))

** Outcome Bad "reverted"

** Storage
(initial)

* Path 24

** Conditions
(iszero (callvalue))
(not 
  (eq? ("transferFrom" 599290589) ("signature" (div (exp 224 2) (calldataload 0)))))
(not (eq? ("approve" 157198259) ("signature" (div (exp 224 2) (calldataload 0)))))
(not (eq? ("withdraw" 773487949) ("signature" (div (exp 224 2) (calldataload 0)))))
(not (eq? ("balanceOf" 1889567281) ("signature" (div (exp 224 2) (calldataload 0)))))
(not (eq? ("totalSupply" 404098525) ("signature" (div (exp 224 2) (calldataload 0)))))
(not (eq? ("allowance" 3714247998) ("signature" (div (exp 224 2) (calldataload 0)))))
(eq? ("transfer" 2835717307) ("signature" (div (exp 224 2) (calldataload 0))))
(not (div (or ("recipient" (calldataload 4)) (caller)) (exp 160 2)))
(not 
  (< 
    ("source balance" (sload (caller) (initial)))
    ("value to be transferred" (calldataload 36))))
(not (eq? (caller) (caller)))
(not 
  (eq? 
    ("allowance" 
      (sload (keccak256 0 32 (set 32 (caller) (set 0 (caller) (initial)))) (initial)))
    ("infinite allowance symbol" (not 1))))
(not 
  (< 
    ("allowance" 
      (sload (keccak256 0 32 (set 32 (caller) (set 0 (caller) (initial)))) (initial)))
    ("value to be transferred" (calldataload 36))))
("overflow" 
  (< 
    ("target balance" (sload ("recipient" (calldataload 4)) (initial)))
    (+ 
      ("target balance" (sload ("recipient" (calldataload 4)) (initial)))
      ("value to be transferred" (calldataload 36)))))

** Outcome Bad "reverted"

** Storage
(set 
  ("target balance" (sload ("recipient" (calldataload 4)) (initial)))
  (- ("value to be transferred" (calldataload 36)) (caller))
  (set 
    ("source balance" (sload (caller) (initial)))
    (- 
      ("value to be transferred" (calldataload 36))
      (keccak256 0 32 (set 32 (caller) (set 0 (caller) (initial)))))
    (initial)))

* Path 25

** Conditions
(iszero (callvalue))
(not 
  (eq? ("transferFrom" 599290589) ("signature" (div (exp 224 2) (calldataload 0)))))
(not (eq? ("approve" 157198259) ("signature" (div (exp 224 2) (calldataload 0)))))
(not (eq? ("withdraw" 773487949) ("signature" (div (exp 224 2) (calldataload 0)))))
(not (eq? ("balanceOf" 1889567281) ("signature" (div (exp 224 2) (calldataload 0)))))
(not (eq? ("totalSupply" 404098525) ("signature" (div (exp 224 2) (calldataload 0)))))
(not (eq? ("allowance" 3714247998) ("signature" (div (exp 224 2) (calldataload 0)))))
(eq? ("transfer" 2835717307) ("signature" (div (exp 224 2) (calldataload 0))))
(not (div (or ("recipient" (calldataload 4)) (caller)) (exp 160 2)))
(not 
  (< 
    ("source balance" (sload (caller) (initial)))
    ("value to be transferred" (calldataload 36))))
(not (eq? (caller) (caller)))
(not 
  (eq? 
    ("allowance" 
      (sload (keccak256 0 32 (set 32 (caller) (set 0 (caller) (initial)))) (initial)))
    ("infinite allowance symbol" (not 1))))
(not 
  (< 
    ("allowance" 
      (sload (keccak256 0 32 (set 32 (caller) (set 0 (caller) (initial)))) (initial)))
    ("value to be transferred" (calldataload 36))))
(not 
  ("overflow" 
    (< 
      ("target balance" (sload ("recipient" (calldataload 4)) (initial)))
      (+ 
        ("target balance" (sload ("recipient" (calldataload 4)) (initial)))
        ("value to be transferred" (calldataload 36))))))

** Outcome Good

** Storage
(set 
  ("recipient" (calldataload 4))
  (+ 
    ("target balance" (sload ("recipient" (calldataload 4)) (initial)))
    ("value to be transferred" (calldataload 36)))
  (set 
    ("target balance" (sload ("recipient" (calldataload 4)) (initial)))
    (- ("value to be transferred" (calldataload 36)) (caller))
    (set 
      ("source balance" (sload (caller) (initial)))
      (- 
        ("value to be transferred" (calldataload 36))
        (keccak256 0 32 (set 32 (caller) (set 0 (caller) (initial)))))
      (initial))))

* Path 26

** Conditions
(iszero (callvalue))
(not 
  (eq? ("transferFrom" 599290589) ("signature" (div (exp 224 2) (calldataload 0)))))
(not (eq? ("approve" 157198259) ("signature" (div (exp 224 2) (calldataload 0)))))
(not (eq? ("withdraw" 773487949) ("signature" (div (exp 224 2) (calldataload 0)))))
(not (eq? ("balanceOf" 1889567281) ("signature" (div (exp 224 2) (calldataload 0)))))
(not (eq? ("totalSupply" 404098525) ("signature" (div (exp 224 2) (calldataload 0)))))
(not (eq? ("allowance" 3714247998) ("signature" (div (exp 224 2) (calldataload 0)))))
(not (eq? ("transfer" 2835717307) ("signature" (div (exp 224 2) (calldataload 0)))))

** Outcome Bad "reverted"

** Storage
(initial)

* Path 27

** Conditions
(not (iszero (callvalue)))
("overflow" 
  (< 
    (callvalue)
    (+ (callvalue) ("total supply" (sload ("total supply slot" (not 1)) (initial))))))

** Outcome Bad "reverted"

** Storage
(initial)

* Path 28

** Conditions
(not (iszero (callvalue)))
(not 
  ("overflow" 
    (< 
      (callvalue)
      (+ 
        (callvalue)
        ("total supply" (sload ("total supply slot" (not 1)) (initial)))))))
("overflow" 
  (< 
    (callvalue)
    (+ 
      (callvalue)
      ("old target balance" 
        (sload 
          (caller)
          (set 
            ("total supply slot" (not 1))
            (+ 
              (callvalue)
              ("total supply" (sload ("total supply slot" (not 1)) (initial))))
            (initial)))))))

** Outcome Bad "reverted"

** Storage
(set 
  ("total supply slot" (not 1))
  (+ (callvalue) ("total supply" (sload ("total supply slot" (not 1)) (initial))))
  (initial))

* Path 29

** Conditions
(not (iszero (callvalue)))
(not 
  ("overflow" 
    (< 
      (callvalue)
      (+ 
        (callvalue)
        ("total supply" (sload ("total supply slot" (not 1)) (initial)))))))
(not 
  ("overflow" 
    (< 
      (callvalue)
      (+ 
        (callvalue)
        ("old target balance" 
          (sload 
            (caller)
            (set 
              ("total supply slot" (not 1))
              (+ 
                (callvalue)
                ("total supply" (sload ("total supply slot" (not 1)) (initial))))
              (initial))))))))
(eq? ("transferFrom" 599290589) ("signature" (div (exp 224 2) (calldataload 0))))
(div (or ("to" (calldataload 36)) ("from" (calldataload 4))) (exp 160 2))

** Outcome Bad "reverted"

** Storage
(set 
  (caller)
  (+ 
    (callvalue)
    ("old target balance" 
      (sload 
        (caller)
        (set 
          ("total supply slot" (not 1))
          (+ 
            (callvalue)
            ("total supply" (sload ("total supply slot" (not 1)) (initial))))
          (initial)))))
  (set 
    ("total supply slot" (not 1))
    (+ (callvalue) ("total supply" (sload ("total supply slot" (not 1)) (initial))))
    (initial)))

* Path 30

** Conditions
(not (iszero (callvalue)))
(not 
  ("overflow" 
    (< 
      (callvalue)
      (+ 
        (callvalue)
        ("total supply" (sload ("total supply slot" (not 1)) (initial)))))))
(not 
  ("overflow" 
    (< 
      (callvalue)
      (+ 
        (callvalue)
        ("old target balance" 
          (sload 
            (caller)
            (set 
              ("total supply slot" (not 1))
              (+ 
                (callvalue)
                ("total supply" (sload ("total supply slot" (not 1)) (initial))))
              (initial))))))))
(eq? ("transferFrom" 599290589) ("signature" (div (exp 224 2) (calldataload 0))))
(not (div (or ("to" (calldataload 36)) ("from" (calldataload 4))) (exp 160 2)))
(< 
  ("source balance" 
    (sload 
      ("from" (calldataload 4))
      (set 
        (caller)
        (+ 
          (callvalue)
          ("old target balance" 
            (sload 
              (caller)
              (set 
                ("total supply slot" (not 1))
                (+ 
                  (callvalue)
                  ("total supply" (sload ("total supply slot" (not 1)) (initial))))
                (initial)))))
        (set 
          ("total supply slot" (not 1))
          (+ 
            (callvalue)
            ("total supply" (sload ("total supply slot" (not 1)) (initial))))
          (initial)))))
  ("value to be transferred" (calldataload 68)))

** Outcome Bad "reverted"

** Storage
(set 
  (caller)
  (+ 
    (callvalue)
    ("old target balance" 
      (sload 
        (caller)
        (set 
          ("total supply slot" (not 1))
          (+ 
            (callvalue)
            ("total supply" (sload ("total supply slot" (not 1)) (initial))))
          (initial)))))
  (set 
    ("total supply slot" (not 1))
    (+ (callvalue) ("total supply" (sload ("total supply slot" (not 1)) (initial))))
    (initial)))

* Path 31

** Conditions
(not (iszero (callvalue)))
(not 
  ("overflow" 
    (< 
      (callvalue)
      (+ 
        (callvalue)
        ("total supply" (sload ("total supply slot" (not 1)) (initial)))))))
(not 
  ("overflow" 
    (< 
      (callvalue)
      (+ 
        (callvalue)
        ("old target balance" 
          (sload 
            (caller)
            (set 
              ("total supply slot" (not 1))
              (+ 
                (callvalue)
                ("total supply" (sload ("total supply slot" (not 1)) (initial))))
              (initial))))))))
(eq? ("transferFrom" 599290589) ("signature" (div (exp 224 2) (calldataload 0))))
(not (div (or ("to" (calldataload 36)) ("from" (calldataload 4))) (exp 160 2)))
(not 
  (< 
    ("source balance" 
      (sload 
        ("from" (calldataload 4))
        (set 
          (caller)
          (+ 
            (callvalue)
            ("old target balance" 
              (sload 
                (caller)
                (set 
                  ("total supply slot" (not 1))
                  (+ 
                    (callvalue)
                    ("total supply" (sload ("total supply slot" (not 1)) (initial))))
                  (initial)))))
          (set 
            ("total supply slot" (not 1))
            (+ 
              (callvalue)
              ("total supply" (sload ("total supply slot" (not 1)) (initial))))
            (initial)))))
    ("value to be transferred" (calldataload 68))))
(eq? (caller) ("from" (calldataload 4)))
("overflow" 
  (< 
    ("target balance" 
      (sload 
        ("to" (calldataload 36))
        (set 
          (caller)
          (+ 
            (callvalue)
            ("old target balance" 
              (sload 
                (caller)
                (set 
                  ("total supply slot" (not 1))
                  (+ 
                    (callvalue)
                    ("total supply" (sload ("total supply slot" (not 1)) (initial))))
                  (initial)))))
          (set 
            ("total supply slot" (not 1))
            (+ 
              (callvalue)
              ("total supply" (sload ("total supply slot" (not 1)) (initial))))
            (initial)))))
    (+ 
      ("target balance" 
        (sload 
          ("to" (calldataload 36))
          (set 
            (caller)
            (+ 
              (callvalue)
              ("old target balance" 
                (sload 
                  (caller)
                  (set 
                    ("total supply slot" (not 1))
                    (+ 
                      (callvalue)
                      ("total supply" (sload ("total supply slot" (not 1)) (initial))))
                    (initial)))))
            (set 
              ("total supply slot" (not 1))
              (+ 
                (callvalue)
                ("total supply" (sload ("total supply slot" (not 1)) (initial))))
              (initial)))))
      ("value to be transferred" (calldataload 68)))))

** Outcome Bad "reverted"

** Storage
(set 
  ("target balance" 
    (sload 
      ("to" (calldataload 36))
      (set 
        (caller)
        (+ 
          (callvalue)
          ("old target balance" 
            (sload 
              (caller)
              (set 
                ("total supply slot" (not 1))
                (+ 
                  (callvalue)
                  ("total supply" (sload ("total supply slot" (not 1)) (initial))))
                (initial)))))
        (set 
          ("total supply slot" (not 1))
          (+ 
            (callvalue)
            ("total supply" (sload ("total supply slot" (not 1)) (initial))))
          (initial)))))
  (- ("value to be transferred" (calldataload 68)) ("from" (calldataload 4)))
  (set 
    (caller)
    (+ 
      (callvalue)
      ("old target balance" 
        (sload 
          (caller)
          (set 
            ("total supply slot" (not 1))
            (+ 
              (callvalue)
              ("total supply" (sload ("total supply slot" (not 1)) (initial))))
            (initial)))))
    (set 
      ("total supply slot" (not 1))
      (+ 
        (callvalue)
        ("total supply" (sload ("total supply slot" (not 1)) (initial))))
      (initial))))

* Path 32

** Conditions
(not (iszero (callvalue)))
(not 
  ("overflow" 
    (< 
      (callvalue)
      (+ 
        (callvalue)
        ("total supply" (sload ("total supply slot" (not 1)) (initial)))))))
(not 
  ("overflow" 
    (< 
      (callvalue)
      (+ 
        (callvalue)
        ("old target balance" 
          (sload 
            (caller)
            (set 
              ("total supply slot" (not 1))
              (+ 
                (callvalue)
                ("total supply" (sload ("total supply slot" (not 1)) (initial))))
              (initial))))))))
(eq? ("transferFrom" 599290589) ("signature" (div (exp 224 2) (calldataload 0))))
(not (div (or ("to" (calldataload 36)) ("from" (calldataload 4))) (exp 160 2)))
(not 
  (< 
    ("source balance" 
      (sload 
        ("from" (calldataload 4))
        (set 
          (caller)
          (+ 
            (callvalue)
            ("old target balance" 
              (sload 
                (caller)
                (set 
                  ("total supply slot" (not 1))
                  (+ 
                    (callvalue)
                    ("total supply" (sload ("total supply slot" (not 1)) (initial))))
                  (initial)))))
          (set 
            ("total supply slot" (not 1))
            (+ 
              (callvalue)
              ("total supply" (sload ("total supply slot" (not 1)) (initial))))
            (initial)))))
    ("value to be transferred" (calldataload 68))))
(eq? (caller) ("from" (calldataload 4)))
(not 
  ("overflow" 
    (< 
      ("target balance" 
        (sload 
          ("to" (calldataload 36))
          (set 
            (caller)
            (+ 
              (callvalue)
              ("old target balance" 
                (sload 
                  (caller)
                  (set 
                    ("total supply slot" (not 1))
                    (+ 
                      (callvalue)
                      ("total supply" (sload ("total supply slot" (not 1)) (initial))))
                    (initial)))))
            (set 
              ("total supply slot" (not 1))
              (+ 
                (callvalue)
                ("total supply" (sload ("total supply slot" (not 1)) (initial))))
              (initial)))))
      (+ 
        ("target balance" 
          (sload 
            ("to" (calldataload 36))
            (set 
              (caller)
              (+ 
                (callvalue)
                ("old target balance" 
                  (sload 
                    (caller)
                    (set 
                      ("total supply slot" (not 1))
                      (+ 
                        (callvalue)
                        ("total supply" (sload ("total supply slot" (not 1)) (initial))))
                      (initial)))))
              (set 
                ("total supply slot" (not 1))
                (+ 
                  (callvalue)
                  ("total supply" (sload ("total supply slot" (not 1)) (initial))))
                (initial)))))
        ("value to be transferred" (calldataload 68))))))

** Outcome Good

** Storage
(set 
  ("to" (calldataload 36))
  (+ 
    ("target balance" 
      (sload 
        ("to" (calldataload 36))
        (set 
          (caller)
          (+ 
            (callvalue)
            ("old target balance" 
              (sload 
                (caller)
                (set 
                  ("total supply slot" (not 1))
                  (+ 
                    (callvalue)
                    ("total supply" (sload ("total supply slot" (not 1)) (initial))))
                  (initial)))))
          (set 
            ("total supply slot" (not 1))
            (+ 
              (callvalue)
              ("total supply" (sload ("total supply slot" (not 1)) (initial))))
            (initial)))))
    ("value to be transferred" (calldataload 68)))
  (set 
    ("target balance" 
      (sload 
        ("to" (calldataload 36))
        (set 
          (caller)
          (+ 
            (callvalue)
            ("old target balance" 
              (sload 
                (caller)
                (set 
                  ("total supply slot" (not 1))
                  (+ 
                    (callvalue)
                    ("total supply" (sload ("total supply slot" (not 1)) (initial))))
                  (initial)))))
          (set 
            ("total supply slot" (not 1))
            (+ 
              (callvalue)
              ("total supply" (sload ("total supply slot" (not 1)) (initial))))
            (initial)))))
    (- ("value to be transferred" (calldataload 68)) ("from" (calldataload 4)))
    (set 
      (caller)
      (+ 
        (callvalue)
        ("old target balance" 
          (sload 
            (caller)
            (set 
              ("total supply slot" (not 1))
              (+ 
                (callvalue)
                ("total supply" (sload ("total supply slot" (not 1)) (initial))))
              (initial)))))
      (set 
        ("total supply slot" (not 1))
        (+ 
          (callvalue)
          ("total supply" (sload ("total supply slot" (not 1)) (initial))))
        (initial)))))

* Path 33

** Conditions
(not (iszero (callvalue)))
(not 
  ("overflow" 
    (< 
      (callvalue)
      (+ 
        (callvalue)
        ("total supply" (sload ("total supply slot" (not 1)) (initial)))))))
(not 
  ("overflow" 
    (< 
      (callvalue)
      (+ 
        (callvalue)
        ("old target balance" 
          (sload 
            (caller)
            (set 
              ("total supply slot" (not 1))
              (+ 
                (callvalue)
                ("total supply" (sload ("total supply slot" (not 1)) (initial))))
              (initial))))))))
(eq? ("transferFrom" 599290589) ("signature" (div (exp 224 2) (calldataload 0))))
(not (div (or ("to" (calldataload 36)) ("from" (calldataload 4))) (exp 160 2)))
(not 
  (< 
    ("source balance" 
      (sload 
        ("from" (calldataload 4))
        (set 
          (caller)
          (+ 
            (callvalue)
            ("old target balance" 
              (sload 
                (caller)
                (set 
                  ("total supply slot" (not 1))
                  (+ 
                    (callvalue)
                    ("total supply" (sload ("total supply slot" (not 1)) (initial))))
                  (initial)))))
          (set 
            ("total supply slot" (not 1))
            (+ 
              (callvalue)
              ("total supply" (sload ("total supply slot" (not 1)) (initial))))
            (initial)))))
    ("value to be transferred" (calldataload 68))))
(not (eq? (caller) ("from" (calldataload 4))))
(eq? 
  ("allowance" 
    (sload 
      (keccak256 
        0
        32
        (set 
          32
          (caller)
          (set 0 ("from" (calldataload 4)) (set 0 (callvalue) (initial)))))
      (set 
        (caller)
        (+ 
          (callvalue)
          ("old target balance" 
            (sload 
              (caller)
              (set 
                ("total supply slot" (not 1))
                (+ 
                  (callvalue)
                  ("total supply" (sload ("total supply slot" (not 1)) (initial))))
                (initial)))))
        (set 
          ("total supply slot" (not 1))
          (+ 
            (callvalue)
            ("total supply" (sload ("total supply slot" (not 1)) (initial))))
          (initial)))))
  ("infinite allowance symbol" (not 1)))
("overflow" 
  (< 
    (keccak256 
      0
      32
      (set 
        32
        (caller)
        (set 0 ("from" (calldataload 4)) (set 0 (callvalue) (initial)))))
    (+ 
      (keccak256 
        0
        32
        (set 
          32
          (caller)
          (set 0 ("from" (calldataload 4)) (set 0 (callvalue) (initial)))))
      ("from" (calldataload 4)))))

** Outcome Bad "reverted"

** Storage
(set 
  (keccak256 
    0
    32
    (set 32 (caller) (set 0 ("from" (calldataload 4)) (set 0 (callvalue) (initial)))))
  (- 
    ("from" (calldataload 4))
    ("source balance" 
      (sload 
        ("from" (calldataload 4))
        (set 
          (caller)
          (+ 
            (callvalue)
            ("old target balance" 
              (sload 
                (caller)
                (set 
                  ("total supply slot" (not 1))
                  (+ 
                    (callvalue)
                    ("total supply" (sload ("total supply slot" (not 1)) (initial))))
                  (initial)))))
          (set 
            ("total supply slot" (not 1))
            (+ 
              (callvalue)
              ("total supply" (sload ("total supply slot" (not 1)) (initial))))
            (initial))))))
  (set 
    (caller)
    (+ 
      (callvalue)
      ("old target balance" 
        (sload 
          (caller)
          (set 
            ("total supply slot" (not 1))
            (+ 
              (callvalue)
              ("total supply" (sload ("total supply slot" (not 1)) (initial))))
            (initial)))))
    (set 
      ("total supply slot" (not 1))
      (+ 
        (callvalue)
        ("total supply" (sload ("total supply slot" (not 1)) (initial))))
      (initial))))

* Path 34

** Conditions
(not (iszero (callvalue)))
(not 
  ("overflow" 
    (< 
      (callvalue)
      (+ 
        (callvalue)
        ("total supply" (sload ("total supply slot" (not 1)) (initial)))))))
(not 
  ("overflow" 
    (< 
      (callvalue)
      (+ 
        (callvalue)
        ("old target balance" 
          (sload 
            (caller)
            (set 
              ("total supply slot" (not 1))
              (+ 
                (callvalue)
                ("total supply" (sload ("total supply slot" (not 1)) (initial))))
              (initial))))))))
(eq? ("transferFrom" 599290589) ("signature" (div (exp 224 2) (calldataload 0))))
(not (div (or ("to" (calldataload 36)) ("from" (calldataload 4))) (exp 160 2)))
(not 
  (< 
    ("source balance" 
      (sload 
        ("from" (calldataload 4))
        (set 
          (caller)
          (+ 
            (callvalue)
            ("old target balance" 
              (sload 
                (caller)
                (set 
                  ("total supply slot" (not 1))
                  (+ 
                    (callvalue)
                    ("total supply" (sload ("total supply slot" (not 1)) (initial))))
                  (initial)))))
          (set 
            ("total supply slot" (not 1))
            (+ 
              (callvalue)
              ("total supply" (sload ("total supply slot" (not 1)) (initial))))
            (initial)))))
    ("value to be transferred" (calldataload 68))))
(not (eq? (caller) ("from" (calldataload 4))))
(eq? 
  ("allowance" 
    (sload 
      (keccak256 
        0
        32
        (set 
          32
          (caller)
          (set 0 ("from" (calldataload 4)) (set 0 (callvalue) (initial)))))
      (set 
        (caller)
        (+ 
          (callvalue)
          ("old target balance" 
            (sload 
              (caller)
              (set 
                ("total supply slot" (not 1))
                (+ 
                  (callvalue)
                  ("total supply" (sload ("total supply slot" (not 1)) (initial))))
                (initial)))))
        (set 
          ("total supply slot" (not 1))
          (+ 
            (callvalue)
            ("total supply" (sload ("total supply slot" (not 1)) (initial))))
          (initial)))))
  ("infinite allowance symbol" (not 1)))
(not 
  ("overflow" 
    (< 
      (keccak256 
        0
        32
        (set 
          32
          (caller)
          (set 0 ("from" (calldataload 4)) (set 0 (callvalue) (initial)))))
      (+ 
        (keccak256 
          0
          32
          (set 
            32
            (caller)
            (set 0 ("from" (calldataload 4)) (set 0 (callvalue) (initial)))))
        ("from" (calldataload 4))))))

** Outcome Good

** Storage
(set 
  ("target balance" 
    (sload 
      ("to" (calldataload 36))
      (set 
        (caller)
        (+ 
          (callvalue)
          ("old target balance" 
            (sload 
              (caller)
              (set 
                ("total supply slot" (not 1))
                (+ 
                  (callvalue)
                  ("total supply" (sload ("total supply slot" (not 1)) (initial))))
                (initial)))))
        (set 
          ("total supply slot" (not 1))
          (+ 
            (callvalue)
            ("total supply" (sload ("total supply slot" (not 1)) (initial))))
          (initial)))))
  (+ 
    (keccak256 
      0
      32
      (set 
        32
        (caller)
        (set 0 ("from" (calldataload 4)) (set 0 (callvalue) (initial)))))
    ("from" (calldataload 4)))
  (set 
    (keccak256 
      0
      32
      (set 
        32
        (caller)
        (set 0 ("from" (calldataload 4)) (set 0 (callvalue) (initial)))))
    (- 
      ("from" (calldataload 4))
      ("source balance" 
        (sload 
          ("from" (calldataload 4))
          (set 
            (caller)
            (+ 
              (callvalue)
              ("old target balance" 
                (sload 
                  (caller)
                  (set 
                    ("total supply slot" (not 1))
                    (+ 
                      (callvalue)
                      ("total supply" (sload ("total supply slot" (not 1)) (initial))))
                    (initial)))))
            (set 
              ("total supply slot" (not 1))
              (+ 
                (callvalue)
                ("total supply" (sload ("total supply slot" (not 1)) (initial))))
              (initial))))))
    (set 
      (caller)
      (+ 
        (callvalue)
        ("old target balance" 
          (sload 
            (caller)
            (set 
              ("total supply slot" (not 1))
              (+ 
                (callvalue)
                ("total supply" (sload ("total supply slot" (not 1)) (initial))))
              (initial)))))
      (set 
        ("total supply slot" (not 1))
        (+ 
          (callvalue)
          ("total supply" (sload ("total supply slot" (not 1)) (initial))))
        (initial)))))

* Path 35

** Conditions
(not (iszero (callvalue)))
(not 
  ("overflow" 
    (< 
      (callvalue)
      (+ 
        (callvalue)
        ("total supply" (sload ("total supply slot" (not 1)) (initial)))))))
(not 
  ("overflow" 
    (< 
      (callvalue)
      (+ 
        (callvalue)
        ("old target balance" 
          (sload 
            (caller)
            (set 
              ("total supply slot" (not 1))
              (+ 
                (callvalue)
                ("total supply" (sload ("total supply slot" (not 1)) (initial))))
              (initial))))))))
(eq? ("transferFrom" 599290589) ("signature" (div (exp 224 2) (calldataload 0))))
(not (div (or ("to" (calldataload 36)) ("from" (calldataload 4))) (exp 160 2)))
(not 
  (< 
    ("source balance" 
      (sload 
        ("from" (calldataload 4))
        (set 
          (caller)
          (+ 
            (callvalue)
            ("old target balance" 
              (sload 
                (caller)
                (set 
                  ("total supply slot" (not 1))
                  (+ 
                    (callvalue)
                    ("total supply" (sload ("total supply slot" (not 1)) (initial))))
                  (initial)))))
          (set 
            ("total supply slot" (not 1))
            (+ 
              (callvalue)
              ("total supply" (sload ("total supply slot" (not 1)) (initial))))
            (initial)))))
    ("value to be transferred" (calldataload 68))))
(not (eq? (caller) ("from" (calldataload 4))))
(not 
  (eq? 
    ("allowance" 
      (sload 
        (keccak256 
          0
          32
          (set 
            32
            (caller)
            (set 0 ("from" (calldataload 4)) (set 0 (callvalue) (initial)))))
        (set 
          (caller)
          (+ 
            (callvalue)
            ("old target balance" 
              (sload 
                (caller)
                (set 
                  ("total supply slot" (not 1))
                  (+ 
                    (callvalue)
                    ("total supply" (sload ("total supply slot" (not 1)) (initial))))
                  (initial)))))
          (set 
            ("total supply slot" (not 1))
            (+ 
              (callvalue)
              ("total supply" (sload ("total supply slot" (not 1)) (initial))))
            (initial)))))
    ("infinite allowance symbol" (not 1))))
(< 
  ("allowance" 
    (sload 
      (keccak256 
        0
        32
        (set 
          32
          (caller)
          (set 0 ("from" (calldataload 4)) (set 0 (callvalue) (initial)))))
      (set 
        (caller)
        (+ 
          (callvalue)
          ("old target balance" 
            (sload 
              (caller)
              (set 
                ("total supply slot" (not 1))
                (+ 
                  (callvalue)
                  ("total supply" (sload ("total supply slot" (not 1)) (initial))))
                (initial)))))
        (set 
          ("total supply slot" (not 1))
          (+ 
            (callvalue)
            ("total supply" (sload ("total supply slot" (not 1)) (initial))))
          (initial)))))
  ("value to be transferred" (calldataload 68)))

** Outcome Bad "reverted"

** Storage
(set 
  (caller)
  (+ 
    (callvalue)
    ("old target balance" 
      (sload 
        (caller)
        (set 
          ("total supply slot" (not 1))
          (+ 
            (callvalue)
            ("total supply" (sload ("total supply slot" (not 1)) (initial))))
          (initial)))))
  (set 
    ("total supply slot" (not 1))
    (+ (callvalue) ("total supply" (sload ("total supply slot" (not 1)) (initial))))
    (initial)))

* Path 36

** Conditions
(not (iszero (callvalue)))
(not 
  ("overflow" 
    (< 
      (callvalue)
      (+ 
        (callvalue)
        ("total supply" (sload ("total supply slot" (not 1)) (initial)))))))
(not 
  ("overflow" 
    (< 
      (callvalue)
      (+ 
        (callvalue)
        ("old target balance" 
          (sload 
            (caller)
            (set 
              ("total supply slot" (not 1))
              (+ 
                (callvalue)
                ("total supply" (sload ("total supply slot" (not 1)) (initial))))
              (initial))))))))
(eq? ("transferFrom" 599290589) ("signature" (div (exp 224 2) (calldataload 0))))
(not (div (or ("to" (calldataload 36)) ("from" (calldataload 4))) (exp 160 2)))
(not 
  (< 
    ("source balance" 
      (sload 
        ("from" (calldataload 4))
        (set 
          (caller)
          (+ 
            (callvalue)
            ("old target balance" 
              (sload 
                (caller)
                (set 
                  ("total supply slot" (not 1))
                  (+ 
                    (callvalue)
                    ("total supply" (sload ("total supply slot" (not 1)) (initial))))
                  (initial)))))
          (set 
            ("total supply slot" (not 1))
            (+ 
              (callvalue)
              ("total supply" (sload ("total supply slot" (not 1)) (initial))))
            (initial)))))
    ("value to be transferred" (calldataload 68))))
(not (eq? (caller) ("from" (calldataload 4))))
(not 
  (eq? 
    ("allowance" 
      (sload 
        (keccak256 
          0
          32
          (set 
            32
            (caller)
            (set 0 ("from" (calldataload 4)) (set 0 (callvalue) (initial)))))
        (set 
          (caller)
          (+ 
            (callvalue)
            ("old target balance" 
              (sload 
                (caller)
                (set 
                  ("total supply slot" (not 1))
                  (+ 
                    (callvalue)
                    ("total supply" (sload ("total supply slot" (not 1)) (initial))))
                  (initial)))))
          (set 
            ("total supply slot" (not 1))
            (+ 
              (callvalue)
              ("total supply" (sload ("total supply slot" (not 1)) (initial))))
            (initial)))))
    ("infinite allowance symbol" (not 1))))
(not 
  (< 
    ("allowance" 
      (sload 
        (keccak256 
          0
          32
          (set 
            32
            (caller)
            (set 0 ("from" (calldataload 4)) (set 0 (callvalue) (initial)))))
        (set 
          (caller)
          (+ 
            (callvalue)
            ("old target balance" 
              (sload 
                (caller)
                (set 
                  ("total supply slot" (not 1))
                  (+ 
                    (callvalue)
                    ("total supply" (sload ("total supply slot" (not 1)) (initial))))
                  (initial)))))
          (set 
            ("total supply slot" (not 1))
            (+ 
              (callvalue)
              ("total supply" (sload ("total supply slot" (not 1)) (initial))))
            (initial)))))
    ("value to be transferred" (calldataload 68))))
("overflow" 
  (< 
    ("target balance" 
      (sload 
        ("to" (calldataload 36))
        (set 
          (caller)
          (+ 
            (callvalue)
            ("old target balance" 
              (sload 
                (caller)
                (set 
                  ("total supply slot" (not 1))
                  (+ 
                    (callvalue)
                    ("total supply" (sload ("total supply slot" (not 1)) (initial))))
                  (initial)))))
          (set 
            ("total supply slot" (not 1))
            (+ 
              (callvalue)
              ("total supply" (sload ("total supply slot" (not 1)) (initial))))
            (initial)))))
    (+ 
      ("target balance" 
        (sload 
          ("to" (calldataload 36))
          (set 
            (caller)
            (+ 
              (callvalue)
              ("old target balance" 
                (sload 
                  (caller)
                  (set 
                    ("total supply slot" (not 1))
                    (+ 
                      (callvalue)
                      ("total supply" (sload ("total supply slot" (not 1)) (initial))))
                    (initial)))))
            (set 
              ("total supply slot" (not 1))
              (+ 
                (callvalue)
                ("total supply" (sload ("total supply slot" (not 1)) (initial))))
              (initial)))))
      ("value to be transferred" (calldataload 68)))))

** Outcome Bad "reverted"

** Storage
(set 
  ("target balance" 
    (sload 
      ("to" (calldataload 36))
      (set 
        (caller)
        (+ 
          (callvalue)
          ("old target balance" 
            (sload 
              (caller)
              (set 
                ("total supply slot" (not 1))
                (+ 
                  (callvalue)
                  ("total supply" (sload ("total supply slot" (not 1)) (initial))))
                (initial)))))
        (set 
          ("total supply slot" (not 1))
          (+ 
            (callvalue)
            ("total supply" (sload ("total supply slot" (not 1)) (initial))))
          (initial)))))
  (- ("value to be transferred" (calldataload 68)) ("from" (calldataload 4)))
  (set 
    ("source balance" 
      (sload 
        ("from" (calldataload 4))
        (set 
          (caller)
          (+ 
            (callvalue)
            ("old target balance" 
              (sload 
                (caller)
                (set 
                  ("total supply slot" (not 1))
                  (+ 
                    (callvalue)
                    ("total supply" (sload ("total supply slot" (not 1)) (initial))))
                  (initial)))))
          (set 
            ("total supply slot" (not 1))
            (+ 
              (callvalue)
              ("total supply" (sload ("total supply slot" (not 1)) (initial))))
            (initial)))))
    (- 
      ("value to be transferred" (calldataload 68))
      (keccak256 
        0
        32
        (set 
          32
          (caller)
          (set 0 ("from" (calldataload 4)) (set 0 (callvalue) (initial))))))
    (set 
      (caller)
      (+ 
        (callvalue)
        ("old target balance" 
          (sload 
            (caller)
            (set 
              ("total supply slot" (not 1))
              (+ 
                (callvalue)
                ("total supply" (sload ("total supply slot" (not 1)) (initial))))
              (initial)))))
      (set 
        ("total supply slot" (not 1))
        (+ 
          (callvalue)
          ("total supply" (sload ("total supply slot" (not 1)) (initial))))
        (initial)))))

* Path 37

** Conditions
(not (iszero (callvalue)))
(not 
  ("overflow" 
    (< 
      (callvalue)
      (+ 
        (callvalue)
        ("total supply" (sload ("total supply slot" (not 1)) (initial)))))))
(not 
  ("overflow" 
    (< 
      (callvalue)
      (+ 
        (callvalue)
        ("old target balance" 
          (sload 
            (caller)
            (set 
              ("total supply slot" (not 1))
              (+ 
                (callvalue)
                ("total supply" (sload ("total supply slot" (not 1)) (initial))))
              (initial))))))))
(eq? ("transferFrom" 599290589) ("signature" (div (exp 224 2) (calldataload 0))))
(not (div (or ("to" (calldataload 36)) ("from" (calldataload 4))) (exp 160 2)))
(not 
  (< 
    ("source balance" 
      (sload 
        ("from" (calldataload 4))
        (set 
          (caller)
          (+ 
            (callvalue)
            ("old target balance" 
              (sload 
                (caller)
                (set 
                  ("total supply slot" (not 1))
                  (+ 
                    (callvalue)
                    ("total supply" (sload ("total supply slot" (not 1)) (initial))))
                  (initial)))))
          (set 
            ("total supply slot" (not 1))
            (+ 
              (callvalue)
              ("total supply" (sload ("total supply slot" (not 1)) (initial))))
            (initial)))))
    ("value to be transferred" (calldataload 68))))
(not (eq? (caller) ("from" (calldataload 4))))
(not 
  (eq? 
    ("allowance" 
      (sload 
        (keccak256 
          0
          32
          (set 
            32
            (caller)
            (set 0 ("from" (calldataload 4)) (set 0 (callvalue) (initial)))))
        (set 
          (caller)
          (+ 
            (callvalue)
            ("old target balance" 
              (sload 
                (caller)
                (set 
                  ("total supply slot" (not 1))
                  (+ 
                    (callvalue)
                    ("total supply" (sload ("total supply slot" (not 1)) (initial))))
                  (initial)))))
          (set 
            ("total supply slot" (not 1))
            (+ 
              (callvalue)
              ("total supply" (sload ("total supply slot" (not 1)) (initial))))
            (initial)))))
    ("infinite allowance symbol" (not 1))))
(not 
  (< 
    ("allowance" 
      (sload 
        (keccak256 
          0
          32
          (set 
            32
            (caller)
            (set 0 ("from" (calldataload 4)) (set 0 (callvalue) (initial)))))
        (set 
          (caller)
          (+ 
            (callvalue)
            ("old target balance" 
              (sload 
                (caller)
                (set 
                  ("total supply slot" (not 1))
                  (+ 
                    (callvalue)
                    ("total supply" (sload ("total supply slot" (not 1)) (initial))))
                  (initial)))))
          (set 
            ("total supply slot" (not 1))
            (+ 
              (callvalue)
              ("total supply" (sload ("total supply slot" (not 1)) (initial))))
            (initial)))))
    ("value to be transferred" (calldataload 68))))
(not 
  ("overflow" 
    (< 
      ("target balance" 
        (sload 
          ("to" (calldataload 36))
          (set 
            (caller)
            (+ 
              (callvalue)
              ("old target balance" 
                (sload 
                  (caller)
                  (set 
                    ("total supply slot" (not 1))
                    (+ 
                      (callvalue)
                      ("total supply" (sload ("total supply slot" (not 1)) (initial))))
                    (initial)))))
            (set 
              ("total supply slot" (not 1))
              (+ 
                (callvalue)
                ("total supply" (sload ("total supply slot" (not 1)) (initial))))
              (initial)))))
      (+ 
        ("target balance" 
          (sload 
            ("to" (calldataload 36))
            (set 
              (caller)
              (+ 
                (callvalue)
                ("old target balance" 
                  (sload 
                    (caller)
                    (set 
                      ("total supply slot" (not 1))
                      (+ 
                        (callvalue)
                        ("total supply" (sload ("total supply slot" (not 1)) (initial))))
                      (initial)))))
              (set 
                ("total supply slot" (not 1))
                (+ 
                  (callvalue)
                  ("total supply" (sload ("total supply slot" (not 1)) (initial))))
                (initial)))))
        ("value to be transferred" (calldataload 68))))))

** Outcome Good

** Storage
(set 
  ("to" (calldataload 36))
  (+ 
    ("target balance" 
      (sload 
        ("to" (calldataload 36))
        (set 
          (caller)
          (+ 
            (callvalue)
            ("old target balance" 
              (sload 
                (caller)
                (set 
                  ("total supply slot" (not 1))
                  (+ 
                    (callvalue)
                    ("total supply" (sload ("total supply slot" (not 1)) (initial))))
                  (initial)))))
          (set 
            ("total supply slot" (not 1))
            (+ 
              (callvalue)
              ("total supply" (sload ("total supply slot" (not 1)) (initial))))
            (initial)))))
    ("value to be transferred" (calldataload 68)))
  (set 
    ("target balance" 
      (sload 
        ("to" (calldataload 36))
        (set 
          (caller)
          (+ 
            (callvalue)
            ("old target balance" 
              (sload 
                (caller)
                (set 
                  ("total supply slot" (not 1))
                  (+ 
                    (callvalue)
                    ("total supply" (sload ("total supply slot" (not 1)) (initial))))
                  (initial)))))
          (set 
            ("total supply slot" (not 1))
            (+ 
              (callvalue)
              ("total supply" (sload ("total supply slot" (not 1)) (initial))))
            (initial)))))
    (- ("value to be transferred" (calldataload 68)) ("from" (calldataload 4)))
    (set 
      ("source balance" 
        (sload 
          ("from" (calldataload 4))
          (set 
            (caller)
            (+ 
              (callvalue)
              ("old target balance" 
                (sload 
                  (caller)
                  (set 
                    ("total supply slot" (not 1))
                    (+ 
                      (callvalue)
                      ("total supply" (sload ("total supply slot" (not 1)) (initial))))
                    (initial)))))
            (set 
              ("total supply slot" (not 1))
              (+ 
                (callvalue)
                ("total supply" (sload ("total supply slot" (not 1)) (initial))))
              (initial)))))
      (- 
        ("value to be transferred" (calldataload 68))
        (keccak256 
          0
          32
          (set 
            32
            (caller)
            (set 0 ("from" (calldataload 4)) (set 0 (callvalue) (initial))))))
      (set 
        (caller)
        (+ 
          (callvalue)
          ("old target balance" 
            (sload 
              (caller)
              (set 
                ("total supply slot" (not 1))
                (+ 
                  (callvalue)
                  ("total supply" (sload ("total supply slot" (not 1)) (initial))))
                (initial)))))
        (set 
          ("total supply slot" (not 1))
          (+ 
            (callvalue)
            ("total supply" (sload ("total supply slot" (not 1)) (initial))))
          (initial))))))

* Path 38

** Conditions
(not (iszero (callvalue)))
(not 
  ("overflow" 
    (< 
      (callvalue)
      (+ 
        (callvalue)
        ("total supply" (sload ("total supply slot" (not 1)) (initial)))))))
(not 
  ("overflow" 
    (< 
      (callvalue)
      (+ 
        (callvalue)
        ("old target balance" 
          (sload 
            (caller)
            (set 
              ("total supply slot" (not 1))
              (+ 
                (callvalue)
                ("total supply" (sload ("total supply slot" (not 1)) (initial))))
              (initial))))))))
(not 
  (eq? ("transferFrom" 599290589) ("signature" (div (exp 224 2) (calldataload 0)))))
(eq? ("approve" 157198259) ("signature" (div (exp 224 2) (calldataload 0))))

** Outcome Good

** Storage
(set 
  (calldataload 36)
  (keccak256 0 64 (set 32 (calldataload 36) (set 0 (caller) (set 0 (callvalue) (initial)))))
  (set 
    (caller)
    (+ 
      (callvalue)
      ("old target balance" 
        (sload 
          (caller)
          (set 
            ("total supply slot" (not 1))
            (+ 
              (callvalue)
              ("total supply" (sload ("total supply slot" (not 1)) (initial))))
            (initial)))))
    (set 
      ("total supply slot" (not 1))
      (+ 
        (callvalue)
        ("total supply" (sload ("total supply slot" (not 1)) (initial))))
      (initial))))

* Path 39

** Conditions
(not (iszero (callvalue)))
(not 
  ("overflow" 
    (< 
      (callvalue)
      (+ 
        (callvalue)
        ("total supply" (sload ("total supply slot" (not 1)) (initial)))))))
(not 
  ("overflow" 
    (< 
      (callvalue)
      (+ 
        (callvalue)
        ("old target balance" 
          (sload 
            (caller)
            (set 
              ("total supply slot" (not 1))
              (+ 
                (callvalue)
                ("total supply" (sload ("total supply slot" (not 1)) (initial))))
              (initial))))))))
(not 
  (eq? ("transferFrom" 599290589) ("signature" (div (exp 224 2) (calldataload 0)))))
(not (eq? ("approve" 157198259) ("signature" (div (exp 224 2) (calldataload 0)))))
(eq? ("withdraw" 773487949) ("signature" (div (exp 224 2) (calldataload 0))))
(> 
  (- 
    (calldataload 4)
    (sload 
      (caller)
      (set 
        (caller)
        (+ 
          (callvalue)
          ("old target balance" 
            (sload 
              (caller)
              (set 
                ("total supply slot" (not 1))
                (+ 
                  (callvalue)
                  ("total supply" (sload ("total supply slot" (not 1)) (initial))))
                (initial)))))
        (set 
          ("total supply slot" (not 1))
          (+ 
            (callvalue)
            ("total supply" (sload ("total supply slot" (not 1)) (initial))))
          (initial)))))
  (sload 
    (caller)
    (set 
      (caller)
      (+ 
        (callvalue)
        ("old target balance" 
          (sload 
            (caller)
            (set 
              ("total supply slot" (not 1))
              (+ 
                (callvalue)
                ("total supply" (sload ("total supply slot" (not 1)) (initial))))
              (initial)))))
      (set 
        ("total supply slot" (not 1))
        (+ 
          (callvalue)
          ("total supply" (sload ("total supply slot" (not 1)) (initial))))
        (initial)))))

** Outcome Bad "reverted"

** Storage
(set 
  (caller)
  (+ 
    (callvalue)
    ("old target balance" 
      (sload 
        (caller)
        (set 
          ("total supply slot" (not 1))
          (+ 
            (callvalue)
            ("total supply" (sload ("total supply slot" (not 1)) (initial))))
          (initial)))))
  (set 
    ("total supply slot" (not 1))
    (+ (callvalue) ("total supply" (sload ("total supply slot" (not 1)) (initial))))
    (initial)))

* Path 40

** Conditions
(not (iszero (callvalue)))
(not 
  ("overflow" 
    (< 
      (callvalue)
      (+ 
        (callvalue)
        ("total supply" (sload ("total supply slot" (not 1)) (initial)))))))
(not 
  ("overflow" 
    (< 
      (callvalue)
      (+ 
        (callvalue)
        ("old target balance" 
          (sload 
            (caller)
            (set 
              ("total supply slot" (not 1))
              (+ 
                (callvalue)
                ("total supply" (sload ("total supply slot" (not 1)) (initial))))
              (initial))))))))
(not 
  (eq? ("transferFrom" 599290589) ("signature" (div (exp 224 2) (calldataload 0)))))
(not (eq? ("approve" 157198259) ("signature" (div (exp 224 2) (calldataload 0)))))
(eq? ("withdraw" 773487949) ("signature" (div (exp 224 2) (calldataload 0))))
(not 
  (> 
    (- 
      (calldataload 4)
      (sload 
        (caller)
        (set 
          (caller)
          (+ 
            (callvalue)
            ("old target balance" 
              (sload 
                (caller)
                (set 
                  ("total supply slot" (not 1))
                  (+ 
                    (callvalue)
                    ("total supply" (sload ("total supply slot" (not 1)) (initial))))
                  (initial)))))
          (set 
            ("total supply slot" (not 1))
            (+ 
              (callvalue)
              ("total supply" (sload ("total supply slot" (not 1)) (initial))))
            (initial)))))
    (sload 
      (caller)
      (set 
        (caller)
        (+ 
          (callvalue)
          ("old target balance" 
            (sload 
              (caller)
              (set 
                ("total supply slot" (not 1))
                (+ 
                  (callvalue)
                  ("total supply" (sload ("total supply slot" (not 1)) (initial))))
                (initial)))))
        (set 
          ("total supply slot" (not 1))
          (+ 
            (callvalue)
            ("total supply" (sload ("total supply slot" (not 1)) (initial))))
          (initial))))))
(iszero 1)

** Outcome Bad "reverted"

** Storage
(arbitrarily-altered 
  (set 
    (not 1)
    (- 
      (not 1)
      (sload 
        (calldataload 4)
        (set 
          (caller)
          (sload 
            (caller)
            (set 
              (caller)
              (+ 
                (callvalue)
                ("old target balance" 
                  (sload 
                    (caller)
                    (set 
                      ("total supply slot" (not 1))
                      (+ 
                        (callvalue)
                        ("total supply" (sload ("total supply slot" (not 1)) (initial))))
                      (initial)))))
              (set 
                ("total supply slot" (not 1))
                (+ 
                  (callvalue)
                  ("total supply" (sload ("total supply slot" (not 1)) (initial))))
                (initial))))
          (set 
            (caller)
            (+ 
              (callvalue)
              ("old target balance" 
                (sload 
                  (caller)
                  (set 
                    ("total supply slot" (not 1))
                    (+ 
                      (callvalue)
                      ("total supply" (sload ("total supply slot" (not 1)) (initial))))
                    (initial)))))
            (set 
              ("total supply slot" (not 1))
              (+ 
                (callvalue)
                ("total supply" (sload ("total supply slot" (not 1)) (initial))))
              (initial))))))
    (set 
      (caller)
      (sload 
        (caller)
        (set 
          (caller)
          (+ 
            (callvalue)
            ("old target balance" 
              (sload 
                (caller)
                (set 
                  ("total supply slot" (not 1))
                  (+ 
                    (callvalue)
                    ("total supply" (sload ("total supply slot" (not 1)) (initial))))
                  (initial)))))
          (set 
            ("total supply slot" (not 1))
            (+ 
              (callvalue)
              ("total supply" (sload ("total supply slot" (not 1)) (initial))))
            (initial))))
      (set 
        (caller)
        (+ 
          (callvalue)
          ("old target balance" 
            (sload 
              (caller)
              (set 
                ("total supply slot" (not 1))
                (+ 
                  (callvalue)
                  ("total supply" (sload ("total supply slot" (not 1)) (initial))))
                (initial)))))
        (set 
          ("total supply slot" (not 1))
          (+ 
            (callvalue)
            ("total supply" (sload ("total supply slot" (not 1)) (initial))))
          (initial))))))

* Path 41

** Conditions
(not (iszero (callvalue)))
(not 
  ("overflow" 
    (< 
      (callvalue)
      (+ 
        (callvalue)
        ("total supply" (sload ("total supply slot" (not 1)) (initial)))))))
(not 
  ("overflow" 
    (< 
      (callvalue)
      (+ 
        (callvalue)
        ("old target balance" 
          (sload 
            (caller)
            (set 
              ("total supply slot" (not 1))
              (+ 
                (callvalue)
                ("total supply" (sload ("total supply slot" (not 1)) (initial))))
              (initial))))))))
(not 
  (eq? ("transferFrom" 599290589) ("signature" (div (exp 224 2) (calldataload 0)))))
(not (eq? ("approve" 157198259) ("signature" (div (exp 224 2) (calldataload 0)))))
(eq? ("withdraw" 773487949) ("signature" (div (exp 224 2) (calldataload 0))))
(not 
  (> 
    (- 
      (calldataload 4)
      (sload 
        (caller)
        (set 
          (caller)
          (+ 
            (callvalue)
            ("old target balance" 
              (sload 
                (caller)
                (set 
                  ("total supply slot" (not 1))
                  (+ 
                    (callvalue)
                    ("total supply" (sload ("total supply slot" (not 1)) (initial))))
                  (initial)))))
          (set 
            ("total supply slot" (not 1))
            (+ 
              (callvalue)
              ("total supply" (sload ("total supply slot" (not 1)) (initial))))
            (initial)))))
    (sload 
      (caller)
      (set 
        (caller)
        (+ 
          (callvalue)
          ("old target balance" 
            (sload 
              (caller)
              (set 
                ("total supply slot" (not 1))
                (+ 
                  (callvalue)
                  ("total supply" (sload ("total supply slot" (not 1)) (initial))))
                (initial)))))
        (set 
          ("total supply slot" (not 1))
          (+ 
            (callvalue)
            ("total supply" (sload ("total supply slot" (not 1)) (initial))))
          (initial))))))
(not (iszero 1))

** Outcome Good

** Storage
(arbitrarily-altered 
  (set 
    (not 1)
    (- 
      (not 1)
      (sload 
        (calldataload 4)
        (set 
          (caller)
          (sload 
            (caller)
            (set 
              (caller)
              (+ 
                (callvalue)
                ("old target balance" 
                  (sload 
                    (caller)
                    (set 
                      ("total supply slot" (not 1))
                      (+ 
                        (callvalue)
                        ("total supply" (sload ("total supply slot" (not 1)) (initial))))
                      (initial)))))
              (set 
                ("total supply slot" (not 1))
                (+ 
                  (callvalue)
                  ("total supply" (sload ("total supply slot" (not 1)) (initial))))
                (initial))))
          (set 
            (caller)
            (+ 
              (callvalue)
              ("old target balance" 
                (sload 
                  (caller)
                  (set 
                    ("total supply slot" (not 1))
                    (+ 
                      (callvalue)
                      ("total supply" (sload ("total supply slot" (not 1)) (initial))))
                    (initial)))))
            (set 
              ("total supply slot" (not 1))
              (+ 
                (callvalue)
                ("total supply" (sload ("total supply slot" (not 1)) (initial))))
              (initial))))))
    (set 
      (caller)
      (sload 
        (caller)
        (set 
          (caller)
          (+ 
            (callvalue)
            ("old target balance" 
              (sload 
                (caller)
                (set 
                  ("total supply slot" (not 1))
                  (+ 
                    (callvalue)
                    ("total supply" (sload ("total supply slot" (not 1)) (initial))))
                  (initial)))))
          (set 
            ("total supply slot" (not 1))
            (+ 
              (callvalue)
              ("total supply" (sload ("total supply slot" (not 1)) (initial))))
            (initial))))
      (set 
        (caller)
        (+ 
          (callvalue)
          ("old target balance" 
            (sload 
              (caller)
              (set 
                ("total supply slot" (not 1))
                (+ 
                  (callvalue)
                  ("total supply" (sload ("total supply slot" (not 1)) (initial))))
                (initial)))))
        (set 
          ("total supply slot" (not 1))
          (+ 
            (callvalue)
            ("total supply" (sload ("total supply slot" (not 1)) (initial))))
          (initial))))))

* Path 42

** Conditions
(not (iszero (callvalue)))
(not 
  ("overflow" 
    (< 
      (callvalue)
      (+ 
        (callvalue)
        ("total supply" (sload ("total supply slot" (not 1)) (initial)))))))
(not 
  ("overflow" 
    (< 
      (callvalue)
      (+ 
        (callvalue)
        ("old target balance" 
          (sload 
            (caller)
            (set 
              ("total supply slot" (not 1))
              (+ 
                (callvalue)
                ("total supply" (sload ("total supply slot" (not 1)) (initial))))
              (initial))))))))
(not 
  (eq? ("transferFrom" 599290589) ("signature" (div (exp 224 2) (calldataload 0)))))
(not (eq? ("approve" 157198259) ("signature" (div (exp 224 2) (calldataload 0)))))
(not (eq? ("withdraw" 773487949) ("signature" (div (exp 224 2) (calldataload 0)))))
(eq? ("balanceOf" 1889567281) ("signature" (div (exp 224 2) (calldataload 0))))

** Outcome Good

** Storage
(set 
  (caller)
  (+ 
    (callvalue)
    ("old target balance" 
      (sload 
        (caller)
        (set 
          ("total supply slot" (not 1))
          (+ 
            (callvalue)
            ("total supply" (sload ("total supply slot" (not 1)) (initial))))
          (initial)))))
  (set 
    ("total supply slot" (not 1))
    (+ (callvalue) ("total supply" (sload ("total supply slot" (not 1)) (initial))))
    (initial)))

* Path 43

** Conditions
(not (iszero (callvalue)))
(not 
  ("overflow" 
    (< 
      (callvalue)
      (+ 
        (callvalue)
        ("total supply" (sload ("total supply slot" (not 1)) (initial)))))))
(not 
  ("overflow" 
    (< 
      (callvalue)
      (+ 
        (callvalue)
        ("old target balance" 
          (sload 
            (caller)
            (set 
              ("total supply slot" (not 1))
              (+ 
                (callvalue)
                ("total supply" (sload ("total supply slot" (not 1)) (initial))))
              (initial))))))))
(not 
  (eq? ("transferFrom" 599290589) ("signature" (div (exp 224 2) (calldataload 0)))))
(not (eq? ("approve" 157198259) ("signature" (div (exp 224 2) (calldataload 0)))))
(not (eq? ("withdraw" 773487949) ("signature" (div (exp 224 2) (calldataload 0)))))
(not (eq? ("balanceOf" 1889567281) ("signature" (div (exp 224 2) (calldataload 0)))))
(eq? ("totalSupply" 404098525) ("signature" (div (exp 224 2) (calldataload 0))))

** Outcome Good

** Storage
(set 
  (caller)
  (+ 
    (callvalue)
    ("old target balance" 
      (sload 
        (caller)
        (set 
          ("total supply slot" (not 1))
          (+ 
            (callvalue)
            ("total supply" (sload ("total supply slot" (not 1)) (initial))))
          (initial)))))
  (set 
    ("total supply slot" (not 1))
    (+ (callvalue) ("total supply" (sload ("total supply slot" (not 1)) (initial))))
    (initial)))

* Path 44

** Conditions
(not (iszero (callvalue)))
(not 
  ("overflow" 
    (< 
      (callvalue)
      (+ 
        (callvalue)
        ("total supply" (sload ("total supply slot" (not 1)) (initial)))))))
(not 
  ("overflow" 
    (< 
      (callvalue)
      (+ 
        (callvalue)
        ("old target balance" 
          (sload 
            (caller)
            (set 
              ("total supply slot" (not 1))
              (+ 
                (callvalue)
                ("total supply" (sload ("total supply slot" (not 1)) (initial))))
              (initial))))))))
(not 
  (eq? ("transferFrom" 599290589) ("signature" (div (exp 224 2) (calldataload 0)))))
(not (eq? ("approve" 157198259) ("signature" (div (exp 224 2) (calldataload 0)))))
(not (eq? ("withdraw" 773487949) ("signature" (div (exp 224 2) (calldataload 0)))))
(not (eq? ("balanceOf" 1889567281) ("signature" (div (exp 224 2) (calldataload 0)))))
(not (eq? ("totalSupply" 404098525) ("signature" (div (exp 224 2) (calldataload 0)))))
(eq? ("allowance" 3714247998) ("signature" (div (exp 224 2) (calldataload 0))))

** Outcome Good

** Storage
(set 
  (caller)
  (+ 
    (callvalue)
    ("old target balance" 
      (sload 
        (caller)
        (set 
          ("total supply slot" (not 1))
          (+ 
            (callvalue)
            ("total supply" (sload ("total supply slot" (not 1)) (initial))))
          (initial)))))
  (set 
    ("total supply slot" (not 1))
    (+ (callvalue) ("total supply" (sload ("total supply slot" (not 1)) (initial))))
    (initial)))

* Path 45

** Conditions
(not (iszero (callvalue)))
(not 
  ("overflow" 
    (< 
      (callvalue)
      (+ 
        (callvalue)
        ("total supply" (sload ("total supply slot" (not 1)) (initial)))))))
(not 
  ("overflow" 
    (< 
      (callvalue)
      (+ 
        (callvalue)
        ("old target balance" 
          (sload 
            (caller)
            (set 
              ("total supply slot" (not 1))
              (+ 
                (callvalue)
                ("total supply" (sload ("total supply slot" (not 1)) (initial))))
              (initial))))))))
(not 
  (eq? ("transferFrom" 599290589) ("signature" (div (exp 224 2) (calldataload 0)))))
(not (eq? ("approve" 157198259) ("signature" (div (exp 224 2) (calldataload 0)))))
(not (eq? ("withdraw" 773487949) ("signature" (div (exp 224 2) (calldataload 0)))))
(not (eq? ("balanceOf" 1889567281) ("signature" (div (exp 224 2) (calldataload 0)))))
(not (eq? ("totalSupply" 404098525) ("signature" (div (exp 224 2) (calldataload 0)))))
(not (eq? ("allowance" 3714247998) ("signature" (div (exp 224 2) (calldataload 0)))))
(eq? ("transfer" 2835717307) ("signature" (div (exp 224 2) (calldataload 0))))
(div (or ("recipient" (calldataload 4)) (caller)) (exp 160 2))

** Outcome Bad "reverted"

** Storage
(set 
  (caller)
  (+ 
    (callvalue)
    ("old target balance" 
      (sload 
        (caller)
        (set 
          ("total supply slot" (not 1))
          (+ 
            (callvalue)
            ("total supply" (sload ("total supply slot" (not 1)) (initial))))
          (initial)))))
  (set 
    ("total supply slot" (not 1))
    (+ (callvalue) ("total supply" (sload ("total supply slot" (not 1)) (initial))))
    (initial)))

* Path 46

** Conditions
(not (iszero (callvalue)))
(not 
  ("overflow" 
    (< 
      (callvalue)
      (+ 
        (callvalue)
        ("total supply" (sload ("total supply slot" (not 1)) (initial)))))))
(not 
  ("overflow" 
    (< 
      (callvalue)
      (+ 
        (callvalue)
        ("old target balance" 
          (sload 
            (caller)
            (set 
              ("total supply slot" (not 1))
              (+ 
                (callvalue)
                ("total supply" (sload ("total supply slot" (not 1)) (initial))))
              (initial))))))))
(not 
  (eq? ("transferFrom" 599290589) ("signature" (div (exp 224 2) (calldataload 0)))))
(not (eq? ("approve" 157198259) ("signature" (div (exp 224 2) (calldataload 0)))))
(not (eq? ("withdraw" 773487949) ("signature" (div (exp 224 2) (calldataload 0)))))
(not (eq? ("balanceOf" 1889567281) ("signature" (div (exp 224 2) (calldataload 0)))))
(not (eq? ("totalSupply" 404098525) ("signature" (div (exp 224 2) (calldataload 0)))))
(not (eq? ("allowance" 3714247998) ("signature" (div (exp 224 2) (calldataload 0)))))
(eq? ("transfer" 2835717307) ("signature" (div (exp 224 2) (calldataload 0))))
(not (div (or ("recipient" (calldataload 4)) (caller)) (exp 160 2)))
(< 
  ("source balance" 
    (sload 
      (caller)
      (set 
        (caller)
        (+ 
          (callvalue)
          ("old target balance" 
            (sload 
              (caller)
              (set 
                ("total supply slot" (not 1))
                (+ 
                  (callvalue)
                  ("total supply" (sload ("total supply slot" (not 1)) (initial))))
                (initial)))))
        (set 
          ("total supply slot" (not 1))
          (+ 
            (callvalue)
            ("total supply" (sload ("total supply slot" (not 1)) (initial))))
          (initial)))))
  ("value to be transferred" (calldataload 36)))

** Outcome Bad "reverted"

** Storage
(set 
  (caller)
  (+ 
    (callvalue)
    ("old target balance" 
      (sload 
        (caller)
        (set 
          ("total supply slot" (not 1))
          (+ 
            (callvalue)
            ("total supply" (sload ("total supply slot" (not 1)) (initial))))
          (initial)))))
  (set 
    ("total supply slot" (not 1))
    (+ (callvalue) ("total supply" (sload ("total supply slot" (not 1)) (initial))))
    (initial)))

* Path 47

** Conditions
(not (iszero (callvalue)))
(not 
  ("overflow" 
    (< 
      (callvalue)
      (+ 
        (callvalue)
        ("total supply" (sload ("total supply slot" (not 1)) (initial)))))))
(not 
  ("overflow" 
    (< 
      (callvalue)
      (+ 
        (callvalue)
        ("old target balance" 
          (sload 
            (caller)
            (set 
              ("total supply slot" (not 1))
              (+ 
                (callvalue)
                ("total supply" (sload ("total supply slot" (not 1)) (initial))))
              (initial))))))))
(not 
  (eq? ("transferFrom" 599290589) ("signature" (div (exp 224 2) (calldataload 0)))))
(not (eq? ("approve" 157198259) ("signature" (div (exp 224 2) (calldataload 0)))))
(not (eq? ("withdraw" 773487949) ("signature" (div (exp 224 2) (calldataload 0)))))
(not (eq? ("balanceOf" 1889567281) ("signature" (div (exp 224 2) (calldataload 0)))))
(not (eq? ("totalSupply" 404098525) ("signature" (div (exp 224 2) (calldataload 0)))))
(not (eq? ("allowance" 3714247998) ("signature" (div (exp 224 2) (calldataload 0)))))
(eq? ("transfer" 2835717307) ("signature" (div (exp 224 2) (calldataload 0))))
(not (div (or ("recipient" (calldataload 4)) (caller)) (exp 160 2)))
(not 
  (< 
    ("source balance" 
      (sload 
        (caller)
        (set 
          (caller)
          (+ 
            (callvalue)
            ("old target balance" 
              (sload 
                (caller)
                (set 
                  ("total supply slot" (not 1))
                  (+ 
                    (callvalue)
                    ("total supply" (sload ("total supply slot" (not 1)) (initial))))
                  (initial)))))
          (set 
            ("total supply slot" (not 1))
            (+ 
              (callvalue)
              ("total supply" (sload ("total supply slot" (not 1)) (initial))))
            (initial)))))
    ("value to be transferred" (calldataload 36))))
(eq? (caller) (caller))
("overflow" 
  (< 
    ("target balance" 
      (sload 
        ("recipient" (calldataload 4))
        (set 
          (caller)
          (+ 
            (callvalue)
            ("old target balance" 
              (sload 
                (caller)
                (set 
                  ("total supply slot" (not 1))
                  (+ 
                    (callvalue)
                    ("total supply" (sload ("total supply slot" (not 1)) (initial))))
                  (initial)))))
          (set 
            ("total supply slot" (not 1))
            (+ 
              (callvalue)
              ("total supply" (sload ("total supply slot" (not 1)) (initial))))
            (initial)))))
    (+ 
      ("target balance" 
        (sload 
          ("recipient" (calldataload 4))
          (set 
            (caller)
            (+ 
              (callvalue)
              ("old target balance" 
                (sload 
                  (caller)
                  (set 
                    ("total supply slot" (not 1))
                    (+ 
                      (callvalue)
                      ("total supply" (sload ("total supply slot" (not 1)) (initial))))
                    (initial)))))
            (set 
              ("total supply slot" (not 1))
              (+ 
                (callvalue)
                ("total supply" (sload ("total supply slot" (not 1)) (initial))))
              (initial)))))
      ("value to be transferred" (calldataload 36)))))

** Outcome Bad "reverted"

** Storage
(set 
  ("target balance" 
    (sload 
      ("recipient" (calldataload 4))
      (set 
        (caller)
        (+ 
          (callvalue)
          ("old target balance" 
            (sload 
              (caller)
              (set 
                ("total supply slot" (not 1))
                (+ 
                  (callvalue)
                  ("total supply" (sload ("total supply slot" (not 1)) (initial))))
                (initial)))))
        (set 
          ("total supply slot" (not 1))
          (+ 
            (callvalue)
            ("total supply" (sload ("total supply slot" (not 1)) (initial))))
          (initial)))))
  (- ("value to be transferred" (calldataload 36)) (caller))
  (set 
    (caller)
    (+ 
      (callvalue)
      ("old target balance" 
        (sload 
          (caller)
          (set 
            ("total supply slot" (not 1))
            (+ 
              (callvalue)
              ("total supply" (sload ("total supply slot" (not 1)) (initial))))
            (initial)))))
    (set 
      ("total supply slot" (not 1))
      (+ 
        (callvalue)
        ("total supply" (sload ("total supply slot" (not 1)) (initial))))
      (initial))))

* Path 48

** Conditions
(not (iszero (callvalue)))
(not 
  ("overflow" 
    (< 
      (callvalue)
      (+ 
        (callvalue)
        ("total supply" (sload ("total supply slot" (not 1)) (initial)))))))
(not 
  ("overflow" 
    (< 
      (callvalue)
      (+ 
        (callvalue)
        ("old target balance" 
          (sload 
            (caller)
            (set 
              ("total supply slot" (not 1))
              (+ 
                (callvalue)
                ("total supply" (sload ("total supply slot" (not 1)) (initial))))
              (initial))))))))
(not 
  (eq? ("transferFrom" 599290589) ("signature" (div (exp 224 2) (calldataload 0)))))
(not (eq? ("approve" 157198259) ("signature" (div (exp 224 2) (calldataload 0)))))
(not (eq? ("withdraw" 773487949) ("signature" (div (exp 224 2) (calldataload 0)))))
(not (eq? ("balanceOf" 1889567281) ("signature" (div (exp 224 2) (calldataload 0)))))
(not (eq? ("totalSupply" 404098525) ("signature" (div (exp 224 2) (calldataload 0)))))
(not (eq? ("allowance" 3714247998) ("signature" (div (exp 224 2) (calldataload 0)))))
(eq? ("transfer" 2835717307) ("signature" (div (exp 224 2) (calldataload 0))))
(not (div (or ("recipient" (calldataload 4)) (caller)) (exp 160 2)))
(not 
  (< 
    ("source balance" 
      (sload 
        (caller)
        (set 
          (caller)
          (+ 
            (callvalue)
            ("old target balance" 
              (sload 
                (caller)
                (set 
                  ("total supply slot" (not 1))
                  (+ 
                    (callvalue)
                    ("total supply" (sload ("total supply slot" (not 1)) (initial))))
                  (initial)))))
          (set 
            ("total supply slot" (not 1))
            (+ 
              (callvalue)
              ("total supply" (sload ("total supply slot" (not 1)) (initial))))
            (initial)))))
    ("value to be transferred" (calldataload 36))))
(eq? (caller) (caller))
(not 
  ("overflow" 
    (< 
      ("target balance" 
        (sload 
          ("recipient" (calldataload 4))
          (set 
            (caller)
            (+ 
              (callvalue)
              ("old target balance" 
                (sload 
                  (caller)
                  (set 
                    ("total supply slot" (not 1))
                    (+ 
                      (callvalue)
                      ("total supply" (sload ("total supply slot" (not 1)) (initial))))
                    (initial)))))
            (set 
              ("total supply slot" (not 1))
              (+ 
                (callvalue)
                ("total supply" (sload ("total supply slot" (not 1)) (initial))))
              (initial)))))
      (+ 
        ("target balance" 
          (sload 
            ("recipient" (calldataload 4))
            (set 
              (caller)
              (+ 
                (callvalue)
                ("old target balance" 
                  (sload 
                    (caller)
                    (set 
                      ("total supply slot" (not 1))
                      (+ 
                        (callvalue)
                        ("total supply" (sload ("total supply slot" (not 1)) (initial))))
                      (initial)))))
              (set 
                ("total supply slot" (not 1))
                (+ 
                  (callvalue)
                  ("total supply" (sload ("total supply slot" (not 1)) (initial))))
                (initial)))))
        ("value to be transferred" (calldataload 36))))))

** Outcome Good

** Storage
(set 
  ("recipient" (calldataload 4))
  (+ 
    ("target balance" 
      (sload 
        ("recipient" (calldataload 4))
        (set 
          (caller)
          (+ 
            (callvalue)
            ("old target balance" 
              (sload 
                (caller)
                (set 
                  ("total supply slot" (not 1))
                  (+ 
                    (callvalue)
                    ("total supply" (sload ("total supply slot" (not 1)) (initial))))
                  (initial)))))
          (set 
            ("total supply slot" (not 1))
            (+ 
              (callvalue)
              ("total supply" (sload ("total supply slot" (not 1)) (initial))))
            (initial)))))
    ("value to be transferred" (calldataload 36)))
  (set 
    ("target balance" 
      (sload 
        ("recipient" (calldataload 4))
        (set 
          (caller)
          (+ 
            (callvalue)
            ("old target balance" 
              (sload 
                (caller)
                (set 
                  ("total supply slot" (not 1))
                  (+ 
                    (callvalue)
                    ("total supply" (sload ("total supply slot" (not 1)) (initial))))
                  (initial)))))
          (set 
            ("total supply slot" (not 1))
            (+ 
              (callvalue)
              ("total supply" (sload ("total supply slot" (not 1)) (initial))))
            (initial)))))
    (- ("value to be transferred" (calldataload 36)) (caller))
    (set 
      (caller)
      (+ 
        (callvalue)
        ("old target balance" 
          (sload 
            (caller)
            (set 
              ("total supply slot" (not 1))
              (+ 
                (callvalue)
                ("total supply" (sload ("total supply slot" (not 1)) (initial))))
              (initial)))))
      (set 
        ("total supply slot" (not 1))
        (+ 
          (callvalue)
          ("total supply" (sload ("total supply slot" (not 1)) (initial))))
        (initial)))))

* Path 49

** Conditions
(not (iszero (callvalue)))
(not 
  ("overflow" 
    (< 
      (callvalue)
      (+ 
        (callvalue)
        ("total supply" (sload ("total supply slot" (not 1)) (initial)))))))
(not 
  ("overflow" 
    (< 
      (callvalue)
      (+ 
        (callvalue)
        ("old target balance" 
          (sload 
            (caller)
            (set 
              ("total supply slot" (not 1))
              (+ 
                (callvalue)
                ("total supply" (sload ("total supply slot" (not 1)) (initial))))
              (initial))))))))
(not 
  (eq? ("transferFrom" 599290589) ("signature" (div (exp 224 2) (calldataload 0)))))
(not (eq? ("approve" 157198259) ("signature" (div (exp 224 2) (calldataload 0)))))
(not (eq? ("withdraw" 773487949) ("signature" (div (exp 224 2) (calldataload 0)))))
(not (eq? ("balanceOf" 1889567281) ("signature" (div (exp 224 2) (calldataload 0)))))
(not (eq? ("totalSupply" 404098525) ("signature" (div (exp 224 2) (calldataload 0)))))
(not (eq? ("allowance" 3714247998) ("signature" (div (exp 224 2) (calldataload 0)))))
(eq? ("transfer" 2835717307) ("signature" (div (exp 224 2) (calldataload 0))))
(not (div (or ("recipient" (calldataload 4)) (caller)) (exp 160 2)))
(not 
  (< 
    ("source balance" 
      (sload 
        (caller)
        (set 
          (caller)
          (+ 
            (callvalue)
            ("old target balance" 
              (sload 
                (caller)
                (set 
                  ("total supply slot" (not 1))
                  (+ 
                    (callvalue)
                    ("total supply" (sload ("total supply slot" (not 1)) (initial))))
                  (initial)))))
          (set 
            ("total supply slot" (not 1))
            (+ 
              (callvalue)
              ("total supply" (sload ("total supply slot" (not 1)) (initial))))
            (initial)))))
    ("value to be transferred" (calldataload 36))))
(not (eq? (caller) (caller)))
(eq? 
  ("allowance" 
    (sload 
      (keccak256 0 32 (set 32 (caller) (set 0 (caller) (set 0 (callvalue) (initial)))))
      (set 
        (caller)
        (+ 
          (callvalue)
          ("old target balance" 
            (sload 
              (caller)
              (set 
                ("total supply slot" (not 1))
                (+ 
                  (callvalue)
                  ("total supply" (sload ("total supply slot" (not 1)) (initial))))
                (initial)))))
        (set 
          ("total supply slot" (not 1))
          (+ 
            (callvalue)
            ("total supply" (sload ("total supply slot" (not 1)) (initial))))
          (initial)))))
  ("infinite allowance symbol" (not 1)))
("overflow" 
  (< 
    (keccak256 0 32 (set 32 (caller) (set 0 (caller) (set 0 (callvalue) (initial)))))
    (+ 
      (keccak256 0 32 (set 32 (caller) (set 0 (caller) (set 0 (callvalue) (initial)))))
      (caller))))

** Outcome Bad "reverted"

** Storage
(set 
  (keccak256 0 32 (set 32 (caller) (set 0 (caller) (set 0 (callvalue) (initial)))))
  (- 
    (caller)
    ("source balance" 
      (sload 
        (caller)
        (set 
          (caller)
          (+ 
            (callvalue)
            ("old target balance" 
              (sload 
                (caller)
                (set 
                  ("total supply slot" (not 1))
                  (+ 
                    (callvalue)
                    ("total supply" (sload ("total supply slot" (not 1)) (initial))))
                  (initial)))))
          (set 
            ("total supply slot" (not 1))
            (+ 
              (callvalue)
              ("total supply" (sload ("total supply slot" (not 1)) (initial))))
            (initial))))))
  (set 
    (caller)
    (+ 
      (callvalue)
      ("old target balance" 
        (sload 
          (caller)
          (set 
            ("total supply slot" (not 1))
            (+ 
              (callvalue)
              ("total supply" (sload ("total supply slot" (not 1)) (initial))))
            (initial)))))
    (set 
      ("total supply slot" (not 1))
      (+ 
        (callvalue)
        ("total supply" (sload ("total supply slot" (not 1)) (initial))))
      (initial))))

* Path 50

** Conditions
(not (iszero (callvalue)))
(not 
  ("overflow" 
    (< 
      (callvalue)
      (+ 
        (callvalue)
        ("total supply" (sload ("total supply slot" (not 1)) (initial)))))))
(not 
  ("overflow" 
    (< 
      (callvalue)
      (+ 
        (callvalue)
        ("old target balance" 
          (sload 
            (caller)
            (set 
              ("total supply slot" (not 1))
              (+ 
                (callvalue)
                ("total supply" (sload ("total supply slot" (not 1)) (initial))))
              (initial))))))))
(not 
  (eq? ("transferFrom" 599290589) ("signature" (div (exp 224 2) (calldataload 0)))))
(not (eq? ("approve" 157198259) ("signature" (div (exp 224 2) (calldataload 0)))))
(not (eq? ("withdraw" 773487949) ("signature" (div (exp 224 2) (calldataload 0)))))
(not (eq? ("balanceOf" 1889567281) ("signature" (div (exp 224 2) (calldataload 0)))))
(not (eq? ("totalSupply" 404098525) ("signature" (div (exp 224 2) (calldataload 0)))))
(not (eq? ("allowance" 3714247998) ("signature" (div (exp 224 2) (calldataload 0)))))
(eq? ("transfer" 2835717307) ("signature" (div (exp 224 2) (calldataload 0))))
(not (div (or ("recipient" (calldataload 4)) (caller)) (exp 160 2)))
(not 
  (< 
    ("source balance" 
      (sload 
        (caller)
        (set 
          (caller)
          (+ 
            (callvalue)
            ("old target balance" 
              (sload 
                (caller)
                (set 
                  ("total supply slot" (not 1))
                  (+ 
                    (callvalue)
                    ("total supply" (sload ("total supply slot" (not 1)) (initial))))
                  (initial)))))
          (set 
            ("total supply slot" (not 1))
            (+ 
              (callvalue)
              ("total supply" (sload ("total supply slot" (not 1)) (initial))))
            (initial)))))
    ("value to be transferred" (calldataload 36))))
(not (eq? (caller) (caller)))
(eq? 
  ("allowance" 
    (sload 
      (keccak256 0 32 (set 32 (caller) (set 0 (caller) (set 0 (callvalue) (initial)))))
      (set 
        (caller)
        (+ 
          (callvalue)
          ("old target balance" 
            (sload 
              (caller)
              (set 
                ("total supply slot" (not 1))
                (+ 
                  (callvalue)
                  ("total supply" (sload ("total supply slot" (not 1)) (initial))))
                (initial)))))
        (set 
          ("total supply slot" (not 1))
          (+ 
            (callvalue)
            ("total supply" (sload ("total supply slot" (not 1)) (initial))))
          (initial)))))
  ("infinite allowance symbol" (not 1)))
(not 
  ("overflow" 
    (< 
      (keccak256 0 32 (set 32 (caller) (set 0 (caller) (set 0 (callvalue) (initial)))))
      (+ 
        (keccak256 0 32 (set 32 (caller) (set 0 (caller) (set 0 (callvalue) (initial)))))
        (caller)))))

** Outcome Good

** Storage
(set 
  ("target balance" 
    (sload 
      ("recipient" (calldataload 4))
      (set 
        (caller)
        (+ 
          (callvalue)
          ("old target balance" 
            (sload 
              (caller)
              (set 
                ("total supply slot" (not 1))
                (+ 
                  (callvalue)
                  ("total supply" (sload ("total supply slot" (not 1)) (initial))))
                (initial)))))
        (set 
          ("total supply slot" (not 1))
          (+ 
            (callvalue)
            ("total supply" (sload ("total supply slot" (not 1)) (initial))))
          (initial)))))
  (+ 
    (keccak256 0 32 (set 32 (caller) (set 0 (caller) (set 0 (callvalue) (initial)))))
    (caller))
  (set 
    (keccak256 0 32 (set 32 (caller) (set 0 (caller) (set 0 (callvalue) (initial)))))
    (- 
      (caller)
      ("source balance" 
        (sload 
          (caller)
          (set 
            (caller)
            (+ 
              (callvalue)
              ("old target balance" 
                (sload 
                  (caller)
                  (set 
                    ("total supply slot" (not 1))
                    (+ 
                      (callvalue)
                      ("total supply" (sload ("total supply slot" (not 1)) (initial))))
                    (initial)))))
            (set 
              ("total supply slot" (not 1))
              (+ 
                (callvalue)
                ("total supply" (sload ("total supply slot" (not 1)) (initial))))
              (initial))))))
    (set 
      (caller)
      (+ 
        (callvalue)
        ("old target balance" 
          (sload 
            (caller)
            (set 
              ("total supply slot" (not 1))
              (+ 
                (callvalue)
                ("total supply" (sload ("total supply slot" (not 1)) (initial))))
              (initial)))))
      (set 
        ("total supply slot" (not 1))
        (+ 
          (callvalue)
          ("total supply" (sload ("total supply slot" (not 1)) (initial))))
        (initial)))))

* Path 51

** Conditions
(not (iszero (callvalue)))
(not 
  ("overflow" 
    (< 
      (callvalue)
      (+ 
        (callvalue)
        ("total supply" (sload ("total supply slot" (not 1)) (initial)))))))
(not 
  ("overflow" 
    (< 
      (callvalue)
      (+ 
        (callvalue)
        ("old target balance" 
          (sload 
            (caller)
            (set 
              ("total supply slot" (not 1))
              (+ 
                (callvalue)
                ("total supply" (sload ("total supply slot" (not 1)) (initial))))
              (initial))))))))
(not 
  (eq? ("transferFrom" 599290589) ("signature" (div (exp 224 2) (calldataload 0)))))
(not (eq? ("approve" 157198259) ("signature" (div (exp 224 2) (calldataload 0)))))
(not (eq? ("withdraw" 773487949) ("signature" (div (exp 224 2) (calldataload 0)))))
(not (eq? ("balanceOf" 1889567281) ("signature" (div (exp 224 2) (calldataload 0)))))
(not (eq? ("totalSupply" 404098525) ("signature" (div (exp 224 2) (calldataload 0)))))
(not (eq? ("allowance" 3714247998) ("signature" (div (exp 224 2) (calldataload 0)))))
(eq? ("transfer" 2835717307) ("signature" (div (exp 224 2) (calldataload 0))))
(not (div (or ("recipient" (calldataload 4)) (caller)) (exp 160 2)))
(not 
  (< 
    ("source balance" 
      (sload 
        (caller)
        (set 
          (caller)
          (+ 
            (callvalue)
            ("old target balance" 
              (sload 
                (caller)
                (set 
                  ("total supply slot" (not 1))
                  (+ 
                    (callvalue)
                    ("total supply" (sload ("total supply slot" (not 1)) (initial))))
                  (initial)))))
          (set 
            ("total supply slot" (not 1))
            (+ 
              (callvalue)
              ("total supply" (sload ("total supply slot" (not 1)) (initial))))
            (initial)))))
    ("value to be transferred" (calldataload 36))))
(not (eq? (caller) (caller)))
(not 
  (eq? 
    ("allowance" 
      (sload 
        (keccak256 0 32 (set 32 (caller) (set 0 (caller) (set 0 (callvalue) (initial)))))
        (set 
          (caller)
          (+ 
            (callvalue)
            ("old target balance" 
              (sload 
                (caller)
                (set 
                  ("total supply slot" (not 1))
                  (+ 
                    (callvalue)
                    ("total supply" (sload ("total supply slot" (not 1)) (initial))))
                  (initial)))))
          (set 
            ("total supply slot" (not 1))
            (+ 
              (callvalue)
              ("total supply" (sload ("total supply slot" (not 1)) (initial))))
            (initial)))))
    ("infinite allowance symbol" (not 1))))
(< 
  ("allowance" 
    (sload 
      (keccak256 0 32 (set 32 (caller) (set 0 (caller) (set 0 (callvalue) (initial)))))
      (set 
        (caller)
        (+ 
          (callvalue)
          ("old target balance" 
            (sload 
              (caller)
              (set 
                ("total supply slot" (not 1))
                (+ 
                  (callvalue)
                  ("total supply" (sload ("total supply slot" (not 1)) (initial))))
                (initial)))))
        (set 
          ("total supply slot" (not 1))
          (+ 
            (callvalue)
            ("total supply" (sload ("total supply slot" (not 1)) (initial))))
          (initial)))))
  ("value to be transferred" (calldataload 36)))

** Outcome Bad "reverted"

** Storage
(set 
  (caller)
  (+ 
    (callvalue)
    ("old target balance" 
      (sload 
        (caller)
        (set 
          ("total supply slot" (not 1))
          (+ 
            (callvalue)
            ("total supply" (sload ("total supply slot" (not 1)) (initial))))
          (initial)))))
  (set 
    ("total supply slot" (not 1))
    (+ (callvalue) ("total supply" (sload ("total supply slot" (not 1)) (initial))))
    (initial)))

* Path 52

** Conditions
(not (iszero (callvalue)))
(not 
  ("overflow" 
    (< 
      (callvalue)
      (+ 
        (callvalue)
        ("total supply" (sload ("total supply slot" (not 1)) (initial)))))))
(not 
  ("overflow" 
    (< 
      (callvalue)
      (+ 
        (callvalue)
        ("old target balance" 
          (sload 
            (caller)
            (set 
              ("total supply slot" (not 1))
              (+ 
                (callvalue)
                ("total supply" (sload ("total supply slot" (not 1)) (initial))))
              (initial))))))))
(not 
  (eq? ("transferFrom" 599290589) ("signature" (div (exp 224 2) (calldataload 0)))))
(not (eq? ("approve" 157198259) ("signature" (div (exp 224 2) (calldataload 0)))))
(not (eq? ("withdraw" 773487949) ("signature" (div (exp 224 2) (calldataload 0)))))
(not (eq? ("balanceOf" 1889567281) ("signature" (div (exp 224 2) (calldataload 0)))))
(not (eq? ("totalSupply" 404098525) ("signature" (div (exp 224 2) (calldataload 0)))))
(not (eq? ("allowance" 3714247998) ("signature" (div (exp 224 2) (calldataload 0)))))
(eq? ("transfer" 2835717307) ("signature" (div (exp 224 2) (calldataload 0))))
(not (div (or ("recipient" (calldataload 4)) (caller)) (exp 160 2)))
(not 
  (< 
    ("source balance" 
      (sload 
        (caller)
        (set 
          (caller)
          (+ 
            (callvalue)
            ("old target balance" 
              (sload 
                (caller)
                (set 
                  ("total supply slot" (not 1))
                  (+ 
                    (callvalue)
                    ("total supply" (sload ("total supply slot" (not 1)) (initial))))
                  (initial)))))
          (set 
            ("total supply slot" (not 1))
            (+ 
              (callvalue)
              ("total supply" (sload ("total supply slot" (not 1)) (initial))))
            (initial)))))
    ("value to be transferred" (calldataload 36))))
(not (eq? (caller) (caller)))
(not 
  (eq? 
    ("allowance" 
      (sload 
        (keccak256 0 32 (set 32 (caller) (set 0 (caller) (set 0 (callvalue) (initial)))))
        (set 
          (caller)
          (+ 
            (callvalue)
            ("old target balance" 
              (sload 
                (caller)
                (set 
                  ("total supply slot" (not 1))
                  (+ 
                    (callvalue)
                    ("total supply" (sload ("total supply slot" (not 1)) (initial))))
                  (initial)))))
          (set 
            ("total supply slot" (not 1))
            (+ 
              (callvalue)
              ("total supply" (sload ("total supply slot" (not 1)) (initial))))
            (initial)))))
    ("infinite allowance symbol" (not 1))))
(not 
  (< 
    ("allowance" 
      (sload 
        (keccak256 0 32 (set 32 (caller) (set 0 (caller) (set 0 (callvalue) (initial)))))
        (set 
          (caller)
          (+ 
            (callvalue)
            ("old target balance" 
              (sload 
                (caller)
                (set 
                  ("total supply slot" (not 1))
                  (+ 
                    (callvalue)
                    ("total supply" (sload ("total supply slot" (not 1)) (initial))))
                  (initial)))))
          (set 
            ("total supply slot" (not 1))
            (+ 
              (callvalue)
              ("total supply" (sload ("total supply slot" (not 1)) (initial))))
            (initial)))))
    ("value to be transferred" (calldataload 36))))
("overflow" 
  (< 
    ("target balance" 
      (sload 
        ("recipient" (calldataload 4))
        (set 
          (caller)
          (+ 
            (callvalue)
            ("old target balance" 
              (sload 
                (caller)
                (set 
                  ("total supply slot" (not 1))
                  (+ 
                    (callvalue)
                    ("total supply" (sload ("total supply slot" (not 1)) (initial))))
                  (initial)))))
          (set 
            ("total supply slot" (not 1))
            (+ 
              (callvalue)
              ("total supply" (sload ("total supply slot" (not 1)) (initial))))
            (initial)))))
    (+ 
      ("target balance" 
        (sload 
          ("recipient" (calldataload 4))
          (set 
            (caller)
            (+ 
              (callvalue)
              ("old target balance" 
                (sload 
                  (caller)
                  (set 
                    ("total supply slot" (not 1))
                    (+ 
                      (callvalue)
                      ("total supply" (sload ("total supply slot" (not 1)) (initial))))
                    (initial)))))
            (set 
              ("total supply slot" (not 1))
              (+ 
                (callvalue)
                ("total supply" (sload ("total supply slot" (not 1)) (initial))))
              (initial)))))
      ("value to be transferred" (calldataload 36)))))

** Outcome Bad "reverted"

** Storage
(set 
  ("target balance" 
    (sload 
      ("recipient" (calldataload 4))
      (set 
        (caller)
        (+ 
          (callvalue)
          ("old target balance" 
            (sload 
              (caller)
              (set 
                ("total supply slot" (not 1))
                (+ 
                  (callvalue)
                  ("total supply" (sload ("total supply slot" (not 1)) (initial))))
                (initial)))))
        (set 
          ("total supply slot" (not 1))
          (+ 
            (callvalue)
            ("total supply" (sload ("total supply slot" (not 1)) (initial))))
          (initial)))))
  (- ("value to be transferred" (calldataload 36)) (caller))
  (set 
    ("source balance" 
      (sload 
        (caller)
        (set 
          (caller)
          (+ 
            (callvalue)
            ("old target balance" 
              (sload 
                (caller)
                (set 
                  ("total supply slot" (not 1))
                  (+ 
                    (callvalue)
                    ("total supply" (sload ("total supply slot" (not 1)) (initial))))
                  (initial)))))
          (set 
            ("total supply slot" (not 1))
            (+ 
              (callvalue)
              ("total supply" (sload ("total supply slot" (not 1)) (initial))))
            (initial)))))
    (- 
      ("value to be transferred" (calldataload 36))
      (keccak256 0 32 (set 32 (caller) (set 0 (caller) (set 0 (callvalue) (initial))))))
    (set 
      (caller)
      (+ 
        (callvalue)
        ("old target balance" 
          (sload 
            (caller)
            (set 
              ("total supply slot" (not 1))
              (+ 
                (callvalue)
                ("total supply" (sload ("total supply slot" (not 1)) (initial))))
              (initial)))))
      (set 
        ("total supply slot" (not 1))
        (+ 
          (callvalue)
          ("total supply" (sload ("total supply slot" (not 1)) (initial))))
        (initial)))))

* Path 53

** Conditions
(not (iszero (callvalue)))
(not 
  ("overflow" 
    (< 
      (callvalue)
      (+ 
        (callvalue)
        ("total supply" (sload ("total supply slot" (not 1)) (initial)))))))
(not 
  ("overflow" 
    (< 
      (callvalue)
      (+ 
        (callvalue)
        ("old target balance" 
          (sload 
            (caller)
            (set 
              ("total supply slot" (not 1))
              (+ 
                (callvalue)
                ("total supply" (sload ("total supply slot" (not 1)) (initial))))
              (initial))))))))
(not 
  (eq? ("transferFrom" 599290589) ("signature" (div (exp 224 2) (calldataload 0)))))
(not (eq? ("approve" 157198259) ("signature" (div (exp 224 2) (calldataload 0)))))
(not (eq? ("withdraw" 773487949) ("signature" (div (exp 224 2) (calldataload 0)))))
(not (eq? ("balanceOf" 1889567281) ("signature" (div (exp 224 2) (calldataload 0)))))
(not (eq? ("totalSupply" 404098525) ("signature" (div (exp 224 2) (calldataload 0)))))
(not (eq? ("allowance" 3714247998) ("signature" (div (exp 224 2) (calldataload 0)))))
(eq? ("transfer" 2835717307) ("signature" (div (exp 224 2) (calldataload 0))))
(not (div (or ("recipient" (calldataload 4)) (caller)) (exp 160 2)))
(not 
  (< 
    ("source balance" 
      (sload 
        (caller)
        (set 
          (caller)
          (+ 
            (callvalue)
            ("old target balance" 
              (sload 
                (caller)
                (set 
                  ("total supply slot" (not 1))
                  (+ 
                    (callvalue)
                    ("total supply" (sload ("total supply slot" (not 1)) (initial))))
                  (initial)))))
          (set 
            ("total supply slot" (not 1))
            (+ 
              (callvalue)
              ("total supply" (sload ("total supply slot" (not 1)) (initial))))
            (initial)))))
    ("value to be transferred" (calldataload 36))))
(not (eq? (caller) (caller)))
(not 
  (eq? 
    ("allowance" 
      (sload 
        (keccak256 0 32 (set 32 (caller) (set 0 (caller) (set 0 (callvalue) (initial)))))
        (set 
          (caller)
          (+ 
            (callvalue)
            ("old target balance" 
              (sload 
                (caller)
                (set 
                  ("total supply slot" (not 1))
                  (+ 
                    (callvalue)
                    ("total supply" (sload ("total supply slot" (not 1)) (initial))))
                  (initial)))))
          (set 
            ("total supply slot" (not 1))
            (+ 
              (callvalue)
              ("total supply" (sload ("total supply slot" (not 1)) (initial))))
            (initial)))))
    ("infinite allowance symbol" (not 1))))
(not 
  (< 
    ("allowance" 
      (sload 
        (keccak256 0 32 (set 32 (caller) (set 0 (caller) (set 0 (callvalue) (initial)))))
        (set 
          (caller)
          (+ 
            (callvalue)
            ("old target balance" 
              (sload 
                (caller)
                (set 
                  ("total supply slot" (not 1))
                  (+ 
                    (callvalue)
                    ("total supply" (sload ("total supply slot" (not 1)) (initial))))
                  (initial)))))
          (set 
            ("total supply slot" (not 1))
            (+ 
              (callvalue)
              ("total supply" (sload ("total supply slot" (not 1)) (initial))))
            (initial)))))
    ("value to be transferred" (calldataload 36))))
(not 
  ("overflow" 
    (< 
      ("target balance" 
        (sload 
          ("recipient" (calldataload 4))
          (set 
            (caller)
            (+ 
              (callvalue)
              ("old target balance" 
                (sload 
                  (caller)
                  (set 
                    ("total supply slot" (not 1))
                    (+ 
                      (callvalue)
                      ("total supply" (sload ("total supply slot" (not 1)) (initial))))
                    (initial)))))
            (set 
              ("total supply slot" (not 1))
              (+ 
                (callvalue)
                ("total supply" (sload ("total supply slot" (not 1)) (initial))))
              (initial)))))
      (+ 
        ("target balance" 
          (sload 
            ("recipient" (calldataload 4))
            (set 
              (caller)
              (+ 
                (callvalue)
                ("old target balance" 
                  (sload 
                    (caller)
                    (set 
                      ("total supply slot" (not 1))
                      (+ 
                        (callvalue)
                        ("total supply" (sload ("total supply slot" (not 1)) (initial))))
                      (initial)))))
              (set 
                ("total supply slot" (not 1))
                (+ 
                  (callvalue)
                  ("total supply" (sload ("total supply slot" (not 1)) (initial))))
                (initial)))))
        ("value to be transferred" (calldataload 36))))))

** Outcome Good

** Storage
(set 
  ("recipient" (calldataload 4))
  (+ 
    ("target balance" 
      (sload 
        ("recipient" (calldataload 4))
        (set 
          (caller)
          (+ 
            (callvalue)
            ("old target balance" 
              (sload 
                (caller)
                (set 
                  ("total supply slot" (not 1))
                  (+ 
                    (callvalue)
                    ("total supply" (sload ("total supply slot" (not 1)) (initial))))
                  (initial)))))
          (set 
            ("total supply slot" (not 1))
            (+ 
              (callvalue)
              ("total supply" (sload ("total supply slot" (not 1)) (initial))))
            (initial)))))
    ("value to be transferred" (calldataload 36)))
  (set 
    ("target balance" 
      (sload 
        ("recipient" (calldataload 4))
        (set 
          (caller)
          (+ 
            (callvalue)
            ("old target balance" 
              (sload 
                (caller)
                (set 
                  ("total supply slot" (not 1))
                  (+ 
                    (callvalue)
                    ("total supply" (sload ("total supply slot" (not 1)) (initial))))
                  (initial)))))
          (set 
            ("total supply slot" (not 1))
            (+ 
              (callvalue)
              ("total supply" (sload ("total supply slot" (not 1)) (initial))))
            (initial)))))
    (- ("value to be transferred" (calldataload 36)) (caller))
    (set 
      ("source balance" 
        (sload 
          (caller)
          (set 
            (caller)
            (+ 
              (callvalue)
              ("old target balance" 
                (sload 
                  (caller)
                  (set 
                    ("total supply slot" (not 1))
                    (+ 
                      (callvalue)
                      ("total supply" (sload ("total supply slot" (not 1)) (initial))))
                    (initial)))))
            (set 
              ("total supply slot" (not 1))
              (+ 
                (callvalue)
                ("total supply" (sload ("total supply slot" (not 1)) (initial))))
              (initial)))))
      (- 
        ("value to be transferred" (calldataload 36))
        (keccak256 0 32 (set 32 (caller) (set 0 (caller) (set 0 (callvalue) (initial))))))
      (set 
        (caller)
        (+ 
          (callvalue)
          ("old target balance" 
            (sload 
              (caller)
              (set 
                ("total supply slot" (not 1))
                (+ 
                  (callvalue)
                  ("total supply" (sload ("total supply slot" (not 1)) (initial))))
                (initial)))))
        (set 
          ("total supply slot" (not 1))
          (+ 
            (callvalue)
            ("total supply" (sload ("total supply slot" (not 1)) (initial))))
          (initial))))))

* Path 54

** Conditions
(not (iszero (callvalue)))
(not 
  ("overflow" 
    (< 
      (callvalue)
      (+ 
        (callvalue)
        ("total supply" (sload ("total supply slot" (not 1)) (initial)))))))
(not 
  ("overflow" 
    (< 
      (callvalue)
      (+ 
        (callvalue)
        ("old target balance" 
          (sload 
            (caller)
            (set 
              ("total supply slot" (not 1))
              (+ 
                (callvalue)
                ("total supply" (sload ("total supply slot" (not 1)) (initial))))
              (initial))))))))
(not 
  (eq? ("transferFrom" 599290589) ("signature" (div (exp 224 2) (calldataload 0)))))
(not (eq? ("approve" 157198259) ("signature" (div (exp 224 2) (calldataload 0)))))
(not (eq? ("withdraw" 773487949) ("signature" (div (exp 224 2) (calldataload 0)))))
(not (eq? ("balanceOf" 1889567281) ("signature" (div (exp 224 2) (calldataload 0)))))
(not (eq? ("totalSupply" 404098525) ("signature" (div (exp 224 2) (calldataload 0)))))
(not (eq? ("allowance" 3714247998) ("signature" (div (exp 224 2) (calldataload 0)))))
(not (eq? ("transfer" 2835717307) ("signature" (div (exp 224 2) (calldataload 0)))))

** Outcome Bad "reverted"

** Storage
(set 
  (caller)
  (+ 
    (callvalue)
    ("old target balance" 
      (sload 
        (caller)
        (set 
          ("total supply slot" (not 1))
          (+ 
            (callvalue)
            ("total supply" (sload ("total supply slot" (not 1)) (initial))))
          (initial)))))
  (set 
    ("total supply slot" (not 1))
    (+ (callvalue) ("total supply" (sload ("total supply slot" (not 1)) (initial))))
    (initial)))

